rec::robotino::api2 C++ interface: rec::robotino::api2::CameraCapabilities Class Reference
rec::robotino::api2::CameraCapabilities Class Reference
Capabilities of Robotino's camera.
#include <CameraCapabilities.h>
Public Member Functions
CameraCapabilities ()
CameraCapabilities (const CameraCapabilities &other)
virtual ~CameraCapabilities ()
CameraCapabilities & operator= (const CameraCapabilities &other)
void setName (const char *name)
const char * name () const
void addFormat (const CameraFormat &format)
CameraFormat format (unsigned int index) const
unsigned int numFormats () const
Public Attributes
bool brightness
bool contrast
bool saturation
bool autoWhiteBalance
bool gain
bool whiteBalanceTemperature
bool backlightCompensation
bool autoExposure
bool exposure
bool autoFocus
bool focus
bool sharpness
Detailed Description
Capabilities of Robotino's camera.
Constructor & Destructor Documentation
rec::robotino::api2::CameraCapabilities::CameraCapabilities () inline
Constructs a CameraCapabilities instance.
rec::robotino::api2::CameraCapabilities::CameraCapabilities (const CameraCapabilities & other) inline
Copies an existing CameraCapabilities instance.
References addFormat(), format(), and setName().
virtual rec::robotino::api2::CameraCapabilities::~CameraCapabilities () inline virtual
Desonstructor.
Member Function Documentation
void rec::robotino::api2::CameraCapabilities::addFormat (const CameraFormat & format) inline
Add a camera format.
Parameters
format CameraFormat to add.
See also
numFormats(), format()
References format().
Referenced by CameraCapabilities(), and operator=().
CameraFormat rec::robotino::api2::CameraCapabilities::format (unsigned int index) const inline
Retrieve a camera format.
Parameters
index Index of the camera format.
Returns
CameraFormat with the given index or empty format if index >= numFormats().
See also
numFormats(), addFormat()
Referenced by addFormat(), CameraCapabilities(), and operator=().
const char* rec::robotino::api2::CameraCapabilities::name () const inline
Read the format name
Returns
Format name
unsigned int rec::robotino::api2::CameraCapabilities::numFormats () const inline
Returns
The number of camera formats.
See also
format(), addFormat()
CameraCapabilities& rec::robotino::api2::CameraCapabilities::operator= (const CameraCapabilities & other) inline
Copies an existing CameraCapabilities instance.
References addFormat(), autoExposure, autoFocus, autoWhiteBalance, backlightCompensation, brightness, contrast, exposure, focus, format(), gain, saturation, setName(), sharpness, and whiteBalanceTemperature.
void rec::robotino::api2::CameraCapabilities::setName (const char * name) inline
Set the format name
Parameters
name Format name
Referenced by CameraCapabilities(), and operator=().
Member Data Documentation
bool rec::robotino::api2::CameraCapabilities::autoExposure
Camera supports auto exposure setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::autoFocus
Camera supports auto focus setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::autoWhiteBalance
Camera supports auto white balance setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::backlightCompensation
Camera supports backlight compensation setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::brightness
Camera supports brightness setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::contrast
Camera supports contrast setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::exposure
Camera supports exposure setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::focus
Camera supports focus setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::gain
Camera supports gain setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::saturation
Camera supports saturation setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::sharpness
Camera supports sharpness setting.
Referenced by operator=().
bool rec::robotino::api2::CameraCapabilities::whiteBalanceTemperature
Camera supports white balance temperature setting.
Referenced by operator=().
The documentation for this class was generated from the following file:
/home/verbeek/srcs/openrobotino/api2/lib/rec/robotino/api2/CameraCapabilities.h