pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["ablaufprogramme.htm","Beispiele &#62; Ablaufprogramme","Ablaufprogramme",""],
["abs.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Betrag","Betrag",""],
["addition.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen &#62; Addition","Addition",""],
["and.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; AND","AND",""],
["and_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; AND &#62; Dialog","Dialog",""],
["and_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; AND &#62; Beispiel","Beispiel",""],
["and_fl.htm","Funktionsblockbibliothek &#62; Logik &#62; Getriggerte Operationen &#62; AND FL","AND FL",""],
["and_fl_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Getriggerte Operationen &#62; AND FL &#62; Dialog","Dialog",""],
["and_fl_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Getriggerte Operationen &#62; AND FL &#62; Beispiel","Beispiel",""],
["cartesian_to_vector.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Transformationen &#62; Kartesisch nach Vektor","Kartesisch nach Vektor",""],
["changelog.htm","Willkommen &#62; Neuerungen","Neuerungen",""],
["change_language.htm","Willkommen &#62; Umschalten der Sprache","Umschalten der Sprache",""],
["connect_to_robotino.htm","Robotino&#174; View benutzen &#62; Sich mit Robotino&#174; verbinden","Sich mit Robotino&#174; verbinden",""],
["controlpanel.htm","Funktionsblockbibliothek &#62; Eingabegeräte &#62; Steuerungsfeld","Steuerungsfeld",""],
["controlpanel_dialog.htm","Funktionsblockbibliothek &#62; Eingabegeräte &#62; Steuerungsfeld &#62; Dialog","Dialog",""],
["controlpanel_example.htm","Funktionsblockbibliothek &#62; Eingabegeräte &#62; Steuerungsfeld &#62; Beispiel","Beispiel",""],
["counter_down.htm","Funktionsblockbibliothek &#62; Logik &#62; Zähler abwärts","Zähler abwärts",""],
["counter_down_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Zähler abwärts &#62; Dialog","Dialog",""],
["counter_up.htm","Funktionsblockbibliothek &#62; Logik &#62; Zähler aufwärts","Zähler aufwärts",""],
["counter_up_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Zähler aufwärts &#62; Dialog","Dialog",""],
["counter_up_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Zähler aufwärts &#62; Beispiel","Beispiel",""],
["create_net.htm","Robotino&#174; View benutzen &#62; Netze zwischen Funktionsblöcken anlegen","Netze zwischen Funktionsblöcke anlegen",""],
["custom.htm","Funktionsblockbibliothek &#62; Benutzerdefiniert","Benutzerdefiniert",""],
["custom_lua.htm","Funktionsblockbibliothek &#62; Benutzerdefiniert &#62; Lua-Skript","Lua-Skript",""],
["custom_lua_dialog.htm","Funktionsblockbibliothek &#62; Benutzerdefiniert &#62; Lua-Skript &#62; Dialog","Dialog",""],
["custom_lua_example.htm","Funktionsblockbibliothek &#62; Benutzerdefiniert &#62; Lua-Skript &#62; Beispiel","Beispiel",""],
["dataexchange.htm","Funktionsblockbibliothek &#62; Datenaustausch","Datenaustausch",""],
["demultiplexer.htm","Funktionsblockbibliothek &#62; Logik &#62; Demultiplexer","Demultiplexer",""],
["demultiplexer_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Demultiplexer &#62; Dialog","Dialog",""],
["demultiplexer_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Demultiplexer &#62; Beispiel","Beispiel",""],
["deprecated_functionblocks.htm","Funktionsblockbibliothek &#62; Veraltete Funktionsblöcke","Veraltete Funktionsblöcke",""],
["devices.htm","Geräte","Geräte",""],
["devices_add_and_edit.htm","Geräte &#62; Anlegen und bearbeiten","Anlegen und bearbeiten",""],
["devices_dataexchange.htm","Geräte &#62; Datenaustausch","Datenaustausch",""],
["devices_dataexchange_client.htm","Geräte &#62; Datenaustausch &#62; Client","Client",""],
["devices_dataexchange_client_dialog.htm","Geräte &#62; Datenaustausch &#62; Client &#62; Dialog","Dialog",""],
["devices_dataexchange_server.htm","Geräte &#62; Datenaustausch &#62; Server","Server",""],
["devices_dataexchange_server_dialog.htm","Geräte &#62; Datenaustausch &#62; Server &#62; Dialog","Dialog",""],
["devices_dataexchange_server_units.htm","Geräte &#62; Datenaustausch &#62; Funktionsblöcke","Funktionsblöcke",""],
["devices_dataexchange_units_reader.htm","Geräte &#62; Datenaustausch &#62; Funktionsblöcke &#62; Leser","Leser",""],
["devices_dataexchange_units_writer.htm","Geräte &#62; Datenaustausch &#62; Funktionsblöcke &#62; Schreiber","Schreiber",""],
["devices_joystick.htm","Geräte &#62; Joystick","Joystick",""],
["devices_localcamera.htm","Geräte &#62; Lokale Kamera","Lokale Kamera",""],
["devices_robotino.htm","Geräte &#62; Robotino","Robotino",""],
["devices_robotino_rangefinder.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Laserscanner","Laserscanner",""],
["devices_show_dialogs.htm","Geräte &#62; Dialog aufrufen","Dialog aufrufen",""],
["device_robotino_charger_dialog.htm","Geräte &#62; Robotino &#62; Akkulader","Akkulader",""],
["device_robotino_connection.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Interne Sensoren &#62; Verbindung","Verbindung",""],
["device_robotino_gyroscope.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Navigation &#62; Gyroskop","Gyroskop",""],
["device_robotino_manipulator.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Manipulator","Manipulator",""],
["device_robotino_manipulator_axescount.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Manipulator &#62; Leser &#62; Anzahl der Achsen","Anzahl der Achsen",""],
["device_robotino_manipulator_axis.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Manipulator &#62; Leser &#62; Achse","Achse",""],
["device_robotino_manipulator_axis_writer.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Manipulator &#62; Schreiber &#62; Achse","Achse",""],
["device_robotino_manipulator_dialog.htm","Geräte &#62; Robotino &#62; Manipulatordialog","Manipulatordialog",""],
["device_robotino_manipulator_functionblocks_reader.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Manipulator &#62; Leser","Leser",""],
["device_robotino_manipulator_functionblocks_writer.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Manipulator &#62; Schreiber","Schreiber",""],
["device_robotino_manipulator_positionselector.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Manipulator &#62; Schreiber &#62; Positionsauswahl","Positionsauswahl",""],
["device_robotino_manipulator_positionselector_dialog.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Manipulator &#62; Schreiber &#62; Positionsauswahl &#62; Dialog","Dialog",""],
["device_robotino_rangefinder_analysis.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Laserscanner &#62; Laserscanner Auswertung","Laserscanner Auswertung",""],
["device_robotino_rangefinder_analysis_dialog.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Laserscanner &#62; Laserscanner Auswertung &#62; Dialog","Dialog",""],
["device_robotino_rangefinder_dialog.htm","Geräte &#62; Robotino &#62; Laserscannerdialog","Laserscannerdialog",""],
["device_robotino_rangefinder_functionblocks.htm","Funktionsblöcke","Funktionsblöcke",""],
["device_robotino_rangefinder_information.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Laserscanner &#62; Laserscanner Information","Laserscanner Information",""],
["device_robotino_rangefinder_rangefinder.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Laserscanner &#62; Laserscanner","Laserscanner",""],
["device_robotino_robotino_xt.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT","Robotino XT",""],
["device_robotino_robotino_xt_actors.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Aktoren","Aktoren",""],
["device_robotino_robotino_xt_actors_bellows.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Aktoren &#62; Balg","Balg",""],
["device_robotino_robotino_xt_actors_gripper_open.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Aktoren &#62; Greifer öffnen / schließen","Greifer öffnen / schließen",""],
["device_robotino_robotino_xt_actors_gripper_rotate.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Aktoren &#62; Greifer rotieren","Greifer rotieren",""],
["device_robotino_robotino_xt_actors_gripper_rotate_example.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Aktoren &#62; Greifer rotieren &#62; Beispiel","Beispiel",""],
["device_robotino_robotino_xt_actors_segment_xy.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Aktoren &#62; Segment XY","Segment XY",""],
["device_robotino_robotino_xt_actors_segment_xy_example.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Aktoren &#62; Segment XY &#62; Beispiel","Beispiel",""],
["device_robotino_robotino_xt_dialog.htm","Geräte &#62; Robotino &#62; Robotino XT","Robotino XT",""],
["device_robotino_robotino_xt_io.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; E/A","E/A",""],
["device_robotino_robotino_xt_io_compressors.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; E/A &#62; Kompressoren","Kompressoren",""],
["device_robotino_robotino_xt_io_foilpot.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; E/A &#62; Folienpotentiometer","Folienpotentiometer",""],
["device_robotino_robotino_xt_io_gripper_valve.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; E/A &#62; Greiferventil","Greiferventil",""],
["device_robotino_robotino_xt_io_pressuresensor.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; E/A &#62; Drucksensor","Drucksensor",""],
["device_robotino_robotino_xt_io_stringpots.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; E/A &#62; Seilzugpotentiometer","Seilzugpotentiometer",""],
["device_robotino_robotino_xt_io_waterdrainvalve.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; E/A &#62; Wasserablassventil","Wasserablassventil",""],
["device_robotino_robotino_xt_sensors.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Sensoren","Sensoren",""],
["device_robotino_robotino_xt_sensors_bellows.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Sensoren &#62; Balg","Balg",""],
["device_udp_dataexchange.htm","Geräte &#62; UDP Datenaustausch","UDP Datenaustausch",""],
["device_udp_dataexchange_checksum.htm","Geräte &#62; UDP Datenaustausch &#62; Protokoll &#62; Prüfsumme","Prüfsumme",""],
["device_udp_dataexchange_dialog.htm","Geräte &#62; UDP Datenaustausch &#62; Dialog","Dialog",""],
["device_udp_dataexchange_example.htm","Geräte &#62; UDP Datenaustausch &#62; Beispiel","Beispiel",""],
["device_udp_dataexchange_functionblocks.htm","Geräte &#62; UDP Datenaustausch &#62; Funktionsblöcke","Funktionsblöcke",""],
["device_udp_dataexchange_functionblocks_message0.htm","Geräte &#62; UDP Datenaustausch &#62; Funktionsblöcke &#62; Nachricht 0","Nachricht 0",""],
["device_udp_dataexchange_functionblocks_message0_input.htm","Geräte &#62; UDP Datenaustausch &#62; Funktionsblöcke &#62; Nachricht 0 &#62; Eingang","Eingang",""],
["device_udp_dataexchange_functionblocks_message0_input_reader.htm","Geräte &#62; UDP Datenaustausch &#62; Funktionsblöcke &#62; Nachricht 0 &#62; Eingang &#62; Leser","Leser",""],
["device_udp_dataexchange_functionblocks_message0_input_writer.htm","Geräte &#62; UDP Datenaustausch &#62; Funktionsblöcke &#62; Nachricht 0 &#62; Ausgang &#62; Schreiber","Schreiber",""],
["device_udp_dataexchange_functionblocks_message0_output.htm","Geräte &#62; UDP Datenaustausch &#62; Funktionsblöcke &#62; Nachricht 0 &#62; Ausgang","Ausgang",""],
["device_udp_dataexchange_functionblocks_message1.htm","Geräte &#62; UDP Datenaustausch &#62; Funktionsblöcke &#62; Nachricht 1","Nachricht 1",""],
["device_udp_dataexchange_protocol.htm","Geräte &#62; UDP Datenaustausch &#62; Protokoll","Protokoll",""],
["device_udp_dataexchange_protocol_0.htm","Geräte &#62; UDP Datenaustausch &#62; Protokoll &#62; Nachricht 0","Nachricht 0",""],
["device_udp_dataexchange_protocol_1.htm","Geräte &#62; UDP Datenaustausch &#62; Protokoll &#62; Nachricht 1","Nachricht 1",""],
["device_udp_dataexchange_types.htm","Geräte &#62; UDP Datenaustausch &#62; Protokoll &#62; Datentypen","Datentypen",""],
["display.htm","Funktionsblockbibliothek &#62; Anzeigen","Anzeigen",""],
["division.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen &#62; Division","Division",""],
["equal.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Vergleichende Operationen &#62; Gleich","Gleich",""],
["examples_logic.htm","Beispiele &#62; Logik","Logik",""],
["examples_logic_flipflop.htm","Beispiele &#62; Logik &#62; FlipFlop","FlipFlop",""],
["examples_logic_multiplexer.htm","Beispiele &#62; Logik &#62; Multiplexer","Multiplexer",""],
["example_array.htm","Beispiele &#62; Felder","Felder",""],
["example_colortracker.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung","Farbverfolgung",""],
["example_colortracker_camera.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung &#62; Kamera","Kamera",""],
["example_colortracker_colorrangefinder.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung &#62; Farbbereichssuche","Farbbereichssuche",""],
["example_colortracker_drivesystem.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung &#62; Antrieb","Antrieb",""],
["example_colortracker_filter.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung &#62; Filter","Filter",""],
["example_colortracker_rotation.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung &#62; Berechnung der Rotation","Berechnung der Rotation",""],
["example_colortracker_segmenttracker1.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung &#62; Segmentverfolgung 1","Segmentverfolgung 1",""],
["example_colortracker_segmenttracker2.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung &#62; Segmentverfolgung 2","Segmentverfolgung 2",""],
["example_colortracker_ymovement.htm","Beispiele &#62; Bildverarbeitung &#62; Farbverfolgung &#62; Berechnung der y-Bewegung","Berechnung der y-Bewegung",""],
["example_grappler.htm","Beispiele &#62; Elektrischer Greifarm für Robotino&#174;","Elektrischer Greifarm für Robotino&#174;",""],
["example_imageprocessing.htm","Beispiele &#62; Bildverarbeitung","Bildverarbeitung",""],
["example_imageprocessing_search_and_approch.htm","Beispiele &#62; Bildverarbeitung &#62; Suchen und annähren","Suchen und annähren",""],
["example_imageprocessing_search_and_approch_approach.htm","Beispiele &#62; Bildverarbeitung &#62; Suchen und annähren &#62; Anfahren","Anfahren",""],
["example_imageprocessing_search_and_approch_approch_setpoint.htm","Beispiele &#62; Bildverarbeitung &#62; Suchen und annähren &#62; Anfahren &#62; Stellgröße (1)","Stellgröße (1)",""],
["example_imageprocessing_search_and_approch_approch_termination.htm","Beispiele &#62; Bildverarbeitung &#62; Suchen und annähren &#62; Anfahren &#62; Abbruchbedingung (2)","Abbruchbedingung (2)",""],
["example_imageprocessing_search_and_approch_rotate.htm","Beispiele &#62; Bildverarbeitung &#62; Suchen und annähren &#62; Drehen","Drehen",""],
["example_imageprocessing_search_and_approch_rotate_imageprocessing.htm","Beispiele &#62; Bildverarbeitung &#62; Suchen und annähren &#62; Drehen &#62; Bildauswertung (1)","Bildauswertung (1)",""],
["example_imageprocessing_search_and_approch_rotate_setpoint.htm","Beispiele &#62; Bildverarbeitung &#62; Suchen und annähren &#62; Drehen &#62; Stellgröße (2)","Stellgröße (2)",""],
["example_imageprocessing_search_and_approch_rotate_termination.htm","Beispiele &#62; Bildverarbeitung &#62; Suchen und annähren &#62; Drehen &#62; Abbruchbedingung (3)","Abbruchbedingung (3)",""],
["filter.htm","Funktionsblockbibliothek &#62; Filter","Filter",""],
["filter_mean.htm","Funktionsblockbibliothek &#62; Filter &#62; Mittelwertfilter","Mittelwertfilter",""],
["filter_mean_dialog.htm","Funktionsblockbibliothek &#62; Filter &#62; Mittelwertfilter &#62; Dialog","Dialog",""],
["float_array_composer.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Felder &#62; Fließkommafeld-Zusammensetzer","Fließkommafeld-Zusammensetzer",""],
["float_array_composer_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Felder &#62; Fließkommafeld-Zusammensetzer &#62; Dialog","Dialog",""],
["float_array_decomposer.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Felder &#62; Fließkommafeld-Zerleger","Fließkommafeld-Zerleger",""],
["float_array_index_access.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Felder &#62; Fließkommafeld Indexzugriff","Fließkommafeld Indexzugriff",""],
["float_array_splitter.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Felder &#62; Fließkommafeld-Zerhacker","Fließkommafeld-Zerhacker",""],
["float_array_splitter_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Felder &#62; Fließkommafeld-Zerhacker &#62; Dialog","Dialog",""],
["float_array_splitter_example.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Felder &#62; Fließkommafeld-Zerhacker &#62; Beispiel","Beispiel",""],
["functionblocklibrary.htm","Kennenlernen des Arbeitsbereiches &#62; Aufbau und Konzept der Bedienoberfläche &#62; Funktionsblockbibliothek","Funktionsblockbibliothek",""],
["function_block_library.htm","Funktionsblockbibliothek","Funktionsblockbibliothek",""],
["generator.htm","Funktionsblockbibliothek &#62; Generatoren","Generatoren",""],
["generators_arbitrary.htm","Funktionsblockbibliothek &#62; Generatoren &#62; Arbiträrgenerator","Arbiträrgenerator",""],
["generators_arbitrary_dialog.htm","Funktionsblockbibliothek &#62; Generatoren &#62; Arbiträrgenerator &#62; Dialog","Dialog",""],
["generators_arbitrary_example.htm","Funktionsblockbibliothek &#62; Generatoren &#62; Arbiträrgenerator &#62; Beispiel","Beispiel",""],
["generators_constant.htm","Funktionsblockbibliothek &#62; Generatoren &#62; Konstante","Konstante",""],
["generators_random.htm","Funktionsblockbibliothek &#62; Generatoren &#62; Zufallsgenerator","Zufallsgenerator",""],
["generators_timer_example.htm","Funktionsblockbibliothek &#62; Generatoren &#62; Zeitbaustein &#62; Beispiel","Beispiel",""],
["getting_started.htm","Robotino&#174; View benutzen","Robotino&#174; View benutzen",""],
["globalvariables.htm","Funktionsblockbibliothek &#62; Variablen","Variablen",""],
["globalvariables_general.htm","Robotino&#174; View benutzen &#62; Globale Variablen","Globale Variablen",""],
["greater.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Vergleichende Operationen &#62; Größer","Größer",""],
["greater_equal.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Vergleichende Operationen &#62; Größer gleich","Größer gleich",""],
["hsv_colorspace.htm","Beispiele &#62; Bildverarbeitung &#62; HSV Farbraum","HSV Farbraum",""],
["imageprocessing.htm","Funktionsblockbibliothek &#62; Bildverarbeitung","Bildverarbeitung",""],
["imageprocessing_calibration.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Kalibrierung","Kalibrierung",""],
["imageprocessing_calibration_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Kalibrierung &#62; Dialog","Dialog",""],
["imageprocessing_calibration_example.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Kalibrierung &#62; Beispiel","Beispiel",""],
["imageprocessing_colorrangefinder.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Farbbereichssuche","Farbbereichssuche",""],
["imageprocessing_colorrangefinder_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Farbbereichssuche &#62; Dialog","Dialog",""],
["imageprocessing_colorrangefinder_example.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Farbbereichssuche &#62; Beispiel","Beispiel",""],
["imageprocessing_colorspace_conversion.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Farbraumkonvertierung","Farbraumkonvertierung",""],
["imageprocessing_colorspace_conversion_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Farbraumkonvertierung &#62; Dialog","Dialog",""],
["imageprocessing_filter.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Filter","Filter",""],
["imageprocessing_filter_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Filter &#62; Dialog","Dialog",""],
["imageprocessing_filter_example.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Filter &#62; Beispiel","Beispiel",""],
["imageprocessing_imageinfo.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Bildinformation","Bildinformation",""],
["imageprocessing_imageinfo_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Bildinformation &#62; Dialog","Dialog",""],
["imageprocessing_imageinfo_example.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Bildinformation &#62; Beispiel","Beispiel",""],
["imageprocessing_linedetector_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Linienerkennung &#62; Dialog","Dialog",""],
["imageprocessing_linedetector_example.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Linienerkennung &#62; Beispiel","Beispiel",""],
["imageprocessing_marker_detection.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Markerdetektion","Markerdetektion",""],
["imageprocessing_marker_detection_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Markerdetektion &#62; Dialog","Dialog",""],
["imageprocessing_marker_position.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Markerposition","Markerposition",""],
["imageprocessing_marker_position_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Markerposition &#62; Dialog","Dialog",""],
["imageprocessing_marker_position_example.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Markerposition &#62; Beispiel","Beispiel",""],
["imageprocessing_roi.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; ROI","ROI",""],
["imageprocessing_roi_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; ROI &#62; Dialog","Dialog",""],
["imageprocessing_roi_example.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; ROI &#62; Beispiel","Beispiel",""],
["imageprocessing_segmenter_dialog.htm","Funktionsblockbibliothek &#62; Veraltete Funktionsblöcke &#62; Segmentierer &#62; Dialog","Dialog",""],
["imageprocessing_segmenter_example.htm","Funktionsblockbibliothek &#62; Veraltete Funktionsblöcke &#62; Segmentierer &#62; Beispiel","Beispiel",""],
["imageprocessing_segmentextractor_dialog.htm","Funktionsblockbibliothek &#62; Veraltete Funktionsblöcke &#62; Segment Extrahierer &#62; Dialog","Dialog",""],
["imageprocessing_segmentextractor_example.htm","Funktionsblockbibliothek &#62; Veraltete Funktionsblöcke &#62; Segment Extrahierer &#62; Beispiel","Beispiel",""],
["imageprocessing_segmenttracker.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Segmentverfolger","Segmentverfolger",""],
["imageprocessing_sgmenttracker_dialog.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Segmentverfolger &#62; Dialog","Dialog",""],
["imageprocessing_sgmenttracker_example.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Segmentverfolger &#62; Beispiel","Beispiel",""],
["imagereader.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Bildleser","Bildleser",""],
["imagereader_dialog.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Bildleser &#62; Dialog","Dialog",""],
["imagereader_example.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Bildleser &#62; Beispiel","Beispiel",""],
["imagewriter.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Bildschreiber","Bildschreiber",""],
["imagewriter_dialog.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Bildschreiber &#62; Dialog","Dialog",""],
["imagewriter_example.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Bildschreiber &#62; Beispiel","Beispiel",""],
["inputdevices.htm","Funktionsblockbibliothek &#62; Eingabegeräte","Eingabegeräte",""],
["inputdevices_slider.htm","Funktionsblockbibliothek &#62; Eingabegeräte &#62; Schieberegler","Schieberegler",""],
["inputdevices_slider_dialog.htm","Funktionsblockbibliothek &#62; Eingabegeräte &#62; Schieberegler &#62; Dialog","Dialog",""],
["insert_functionblocks.htm","Robotino&#174; View benutzen &#62; Funktionsblöcke einfügen","Funktionsblöcke in ein Programm einfügen",""],
["install_update_uninstall.htm","Willkommen &#62; Installation, Update und Deinstallation","Installation, Update und Deinstallation",""],
["joystick_axis.htm","Geräte &#62; Joystick &#62; Funktionsblöcke &#62; Achse","Achse",""],
["joystick_button.htm","Geräte &#62; Joystick &#62; Funktionsblöcke &#62; Knopf","Knopf",""],
["joystick_dialog.htm","Geräte &#62; Joystick &#62; Dialog","Dialog",""],
["joystick_functionblocks.htm","Geräte &#62; Joystick &#62; Funktionsblöcke","Funktionsblöcke",""],
["keyboard_layout.htm","Robotino&#174; View benutzen &#62; Tastaturbelegung","Tastaturbelegung",""],
["laserrangefinder_data_display.htm","Funktionsblockbibliothek &#62; Anzeigen &#62; Laserscanner Datenanzeige","Laserscanner Datenanzeige",""],
["laserrangefinder_data_display_dialog.htm","Funktionsblockbibliothek &#62; Anzeigen &#62; Laserscanner Datenanzeige &#62; Dialog","Dialog",""],
["legal_notice.htm","Rechtliche Hinweise","Rechtliche Hinweise",""],
["less.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Vergleichende Operationen &#62; Kleiner","Kleiner",""],
["less_equal.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Vergleichende Operationen &#62; Kleiner gleich","Kleiner gleich",""],
["linedetector.htm","Funktionsblockbibliothek &#62; Bildverarbeitung &#62; Linienerkennung","Linienerkennung",""],
["load_state.htm","Robotino&#174; View benutzen &#62; Ein bestehendes Projekt laden","Ein bestehendes Projekt laden",""],
["localcamera_camera.htm","Geräte &#62; Lokale Kamera &#62; Funktionsblöcke &#62; Kamera","Kamera",""],
["localcamera_camera_dialog.htm","Geräte &#62; Lokale Kamera &#62; Funktionsblöcke &#62; Kamera &#62; Dialog","Dialog",""],
["localcamera_dialog.htm","Geräte &#62; Lokale Kamera &#62; Dialog","Dialog",""],
["localcamera_functionblocks.htm","Geräte &#62; Lokale Kamera &#62; Funktionsblöcke","Funktionsblöcke",""],
["logic.htm","Funktionsblockbibliothek &#62; Logik","Logik",""],
["logic_bitwise.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen","Bitweise Operationen",""],
["logic_bitwise_and.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Und","Bitweises Und",""],
["logic_bitwise_and_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Und &#62; Beispiel","Beispiel",""],
["logic_bitwise_leftshift.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Linksschieben","Bitweises Linksschieben",""],
["logic_bitwise_leftshift_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Linksschieben &#62; Beispiel","Beispiel",""],
["logic_bitwise_not.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises NOT","Bitweises NOT",""],
["logic_bitwise_not_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises NOT &#62; Beispiel","Beispiel",""],
["logic_bitwise_or.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Oder","Bitweises Oder",""],
["logic_bitwise_or_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Oder &#62; Beispiel","Beispiel",""],
["logic_bitwise_rightshift.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Rechtsschieben","Bitweises Rechtsschieben",""],
["logic_bitwise_rightshift_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Rechtsschieben &#62; Beispiel","Beispiel",""],
["logic_bitwise_test.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweiser Test","Bitweiser Test",""],
["logic_bitwise_test_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweiser Test &#62; Beispiel","Beispiel",""],
["logic_bitwise_xor.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Exklusiv-Oder","Bitweises Exklusiv-Oder",""],
["logic_bitwise_xor_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Bitweise Operationen &#62; Bitweises Exklusiv-Oder &#62; Beispiel","Beispiel",""],
["logic_ops.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen","Logische Operationen",""],
["logic_triggered.htm","Funktionsblockbibliothek &#62; Logik &#62; Getriggerte Operationen","Getriggerte Operationen",""],
["math.htm","Funktionsblockbibliothek &#62; Mathematik","Mathematik",""],
["math_arithops.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen","Arithmetische Operationen",""],
["math_arithops_sub_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen &#62; Subtraktion &#62; Dialog","Dialog",""],
["math_arithpos_addition_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen &#62; Addition &#62; Dialog","Dialog",""],
["math_arithpos_mult_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen &#62; Multiplikation &#62; Dialog","Dialog",""],
["math_arrays.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Felder","Felder",""],
["math_compops.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Vergleichende Operationen","Vergleichende Operationen",""],
["math_func.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen","Funktionen",""],
["math_funcs_scale.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Skalierung","Skalierung",""],
["math_func_max_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Maximum &#62; Dialog","Dialog",""],
["math_func_min_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Minimum &#62; Dialog","Dialog",""],
["math_func_scale_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Skalierung &#62; Dialog","Dialog",""],
["math_func_transfer_dialog.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Transferfunktion &#62; Dialog","Dialog",""],
["math_func_transfer_example.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Transferfunktion &#62; Beispiel","Beispiel",""],
["maximum.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Maximum","Maximum",""],
["minimum.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Minimum","Minimum",""],
["modulo.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen &#62; Modulo","Modulo",""],
["multiplexer.htm","Funktionsblockbibliothek &#62; Logik &#62; Multiplexer","Multiplexer",""],
["multiplexer_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Multiplexer &#62; Dialog","Dialog",""],
["multiplexer_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Multiplexer &#62; Beispiel","Beispiel",""],
["multiplication.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen &#62; Multiplikation","Multiplikation",""],
["nand.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; NAND","NAND",""],
["nand_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; NAND &#62; Dialog","Dialog",""],
["nand_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; NAND &#62; Beispiel","Beispiel",""],
["nand_fl.htm","Funktionsblockbibliothek &#62; Logik &#62; Getriggerte Operationen &#62; NAND_FL","NAND FL",""],
["nand_fl_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Getriggerte Operationen &#62; NAND_FL &#62; Dialog","Dialog",""],
["navigation.htm","Funktionsblockbibliothek &#62; Navigation","Navigation",""],
["navigation_constant_pose.htm","Funktionsblockbibliothek &#62; Navigation &#62; Konstante Pose","Konstante Pose",""],
["navigation_obstacle_avoidance.htm","Funktionsblockbibliothek &#62; Navigation &#62; Hindernisvermeidung","Hindernisvermeidung",""],
["navigation_obstacle_avoidance_dialog.htm","Funktionsblockbibliothek &#62; Navigation &#62; Hindernisvermeidung &#62; Dialog","Dialog",""],
["navigation_path_composer.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegzusammensetzer","Wegzusammensetzer",""],
["navigation_path_composer_dialog.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegzusammensetzer &#62; Dialog","Dialog",""],
["navigation_path_configuration_dialog1.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegbefahrer &#62; Konfigurationsdialog 1","Konfigurationsdialog 1",""],
["navigation_path_configuration_dialog2.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegbefahrer &#62; Konfigurationsdialog 2","Konfigurationsdialog 2",""],
["navigation_path_configuration_dialog3.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegbefahrer &#62; Konfigurationsdialog 3","Konfigurationsdialog 3",""],
["navigation_path_decomposer.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegzerleger","Wegzerleger",""],
["navigation_path_driver.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegbefahrer","Wegbefahrer",""],
["navigation_path_driver_example.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegbefahrer &#62; Beispiel","Beispiel",""],
["navigation_path_driver_strategy.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegbefahrer &#62; Strategie","Strategie",""],
["navigation_path_path_dialog.htm","Funktionsblockbibliothek &#62; Navigation &#62; Wegbefahrer &#62; Wegansicht","Wegansicht",""],
["navigation_pose_composer.htm","Funktionsblockbibliothek &#62; Navigation &#62; Posenzusammensetzer","Posenzusammensetzer",""],
["navigation_pose_composer_dialog.htm","Funktionsblockbibliothek &#62; Navigation &#62; Posenzusammensetzer &#62; Dialog","Dialog",""],
["navigation_pose_decomposer.htm","Funktionsblockbibliothek &#62; Navigation &#62; Posenzerleger","Posenzerleger",""],
["navigation_pose_decomposer_dialog.htm","Funktionsblockbibliothek &#62; Navigation &#62; Posenzerleger &#62; Dialog","Dialog",""],
["navigation_positiondriver.htm","Funktionsblockbibliothek &#62; Navigation &#62; Positionsfahrer","Positionsfahrer",""],
["new_state.htm","Robotino&#174; View benutzen &#62; Ein neues Projekt erstellen","Ein neues Projekt erstellen",""],
["nor.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; NOR","NOR",""],
["nor_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; NOR &#62; Dialog","Dialog",""],
["nor_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; NOR &#62; Beispiel","Beispiel",""],
["not.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; NOT","NOT",""],
["not_dialog.htm","Dialog","Dialog",""],
["not_equal.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Vergleichende Operationen &#62; Ungleich","Ungleich",""],
["not_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; NOT &#62; Beispiel","Beispiel",""],
["omnidrive_dialog.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Antriebssystem &#62; Omniantrieb &#62; Dialog","Dialog",""],
["omnidrive_inv_dialog.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Antriebssystem &#62; Omniantrieb Invers &#62; Dialog","Dialog",""],
["opcclient.htm","Geräte &#62; OPC Client","OPC Client",""],
["opcclient_analoginput.htm","Geräte &#62; OPC Client &#62; Funktionsblöcke &#62; Eingänge &#62; Analoger Eingang","Analoger Eingang",""],
["opcclient_analogoutput.htm","Geräte &#62; OPC Client &#62; Funktionsblöcke &#62; Ausgänge &#62; Analoger Ausgang","Analoger Ausgang",""],
["opcclient_dialog.htm","Geräte &#62; OPC Client &#62; Dialog","Dialog",""],
["opcclient_digitalinput.htm","Geräte &#62; OPC Client &#62; Funktionsblöcke &#62; Eingänge &#62; Digitaler Eingang","Digitaler Eingang",""],
["opcclient_digitaloutput.htm","Geräte &#62; OPC Client &#62; Funktionsblöcke &#62; Ausgänge &#62; Digitaler Ausgang","Digitaler Ausgang",""],
["opcclient_functionblocks.htm","Geräte &#62; OPC Client &#62; Funktionsblöcke","Funktionsblöcke",""],
["opcclient_inputs.htm","Geräte &#62; OPC Client &#62; Funktionsblöcke &#62; Eingänge","Eingänge",""],
["opcclient_outputs.htm","Geräte &#62; OPC Client &#62; Funktionsblöcke &#62; Ausgänge","Ausgänge",""],
["or.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; OR","OR",""],
["or_dialog.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; OR &#62; Dialog","Dialog",""],
["or_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; OR &#62; Beispiel","Beispiel",""],
["polar_to_vector.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Transformationen &#62; Polar nach Vektor","Polar nach Vektor",""],
["positiondriver_dialog.htm","Funktionsblockbibliothek &#62; Navigation &#62; Positionsfahrer &#62; Dialog","Dialog",""],
["positiondriver_example.htm","Funktionsblockbibliothek &#62; Navigation &#62; Positionsfahrer &#62; Beispiel","Beispiel",""],
["positiondriver_movements.htm","Funktionsblockbibliothek &#62; Navigation &#62; Positionsfahrer &#62; Bewegungen","Bewegungen",""],
["programming.htm","Programmierung","Programmierung",""],
["programming_myfunctionblocks.htm","Programmierung &#62; Eigene Funktionsblöcke","Eigene Funktionsblöcke",""],
["programming_myfunctionblocks_newblock.htm","Programmierung &#62; Eigene Funktionsblöcke &#62; Erstellen eines neuen Funktionsblocks","Erstellen eines neuen Funktionsblocks",""],
["programming_myfunctionblocks_preparation.htm","Programmierung &#62; Eigene Funktionsblöcke &#62; Vorbereiten der Entwicklungsumgebung","Vorbereiten der Entwicklungsumgebung",""],
["programming_myfunctionblocks_robotino.htm","Programmierung &#62; Eigene Funktionsblöcke &#62; Einsatz auf Robotino","Einsatz auf Robotino",""],
["robotino_analoginput.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Anschluss &#62; Analoger Eingang","Analoger Eingang",""],
["robotino_battery.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Interne Sensoren &#62; Batterie","Batterie",""],
["robotino_battery_example.htm","Beispiel","Beispiel",""],
["robotino_bumper.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Kollisionserkennung &#62; Stoßleiste","Stoßleiste",""],
["robotino_camera.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Bildaufnahme &#62; Kamera","Kamera",""],
["robotino_camera_dialog.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Bildaufnahme &#62; Kamera &#62; Dialog","Dialog",""],
["robotino_collisiondetection.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Kollisionserkennung","Kollisionserkennung",""],
["robotino_dialog.htm","Geräte &#62; Robotino &#62; Hauptdialog","Hauptdialog",""],
["robotino_digitalinput.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Anschluss &#62; Digitaler Eingang","Digitaler Eingang",""],
["robotino_digitaloutput.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Anschluss &#62; Digitaler Ausgang","Digitaler Ausgang",""],
["robotino_distance.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Kollisionserkennung &#62; Abstandssensoren","Abstand",""],
["robotino_distancesensor_example.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Kollisionserkennung &#62; Abstandssensoren &#62; Beispiel","Beispiel",""],
["robotino_drivesystem.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Antriebssystem","Antriebssystem",""],
["robotino_drivesystem_functionblock.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Antriebssystem &#62; Antriebssystem","Antriebssystem",""],
["robotino_encoderinput.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Erweiterung &#62; Drehgebereingang","Drehgebereingang",""],
["robotino_functionblocks.htm","Geräte &#62; Robotino &#62; Funktionsblöcke","Funktionsblöcke",""],
["robotino_gripper.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Erweiterung &#62; Greifer","Greifer",""],
["robotino_imagesystem.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Bildaufnahme","Bildaufnahme",""],
["robotino_internalsensors.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Interne Sensoren","Interne Sensoren",""],
["robotino_ioconnector.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Anschluss","E/A Anschluss",""],
["robotino_ioextension.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Erweiterung","E/A Erweiterung",""],
["robotino_motor.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Antriebssystem &#62; Motor","Motor",""],
["robotino_motor_dialog.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Antriebssystem &#62; Motor &#62; Dialog","Dialog",""],
["robotino_navigation.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Navigation","Navigation",""],
["robotino_northstar.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Navigation &#62; North Star","North Star",""],
["robotino_northstar_dialog.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Navigation &#62; North Star &#62; Dialog","Dialog",""],
["robotino_northstar_example.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Navigation &#62; North Star &#62; Beispiel","Beispiel",""],
["robotino_odometry.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Navigation &#62; Odometrie","Odometrie",""],
["robotino_omnidrive.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Antriebssystem &#62; Omniantrieb","Omniantrieb",""],
["robotino_omnidrive_inv.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Antriebssystem &#62; Omniantrieb Invers","Omniantrieb Invers",""],
["robotino_powermanagement.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Interne Sensoren &#62; Stromüberwachung","Stromüberwachung",""],
["robotino_poweroutput.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Erweiterung &#62; Leistungsausgang","Leistungsausgang",""],
["robotino_relais.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; E/A Anschluss &#62; Relais","Relais",""],
["robotino_shutdown.htm","Funktionsblockbibliothek &#62; Veraltete Funktionsblöcke &#62; Ausschalten","Ausschalten",""],
["robotino_toolbar.htm","Geräte &#62; Robotino &#62; Werkzeugleiste","Werkzeugleiste",""],
["robotino_xt_bellows_numbering.htm","Geräte &#62; Robotino &#62; Funktionsblöcke &#62; Robotino XT &#62; Nummerierung der Bälge","Nummerierung der Bälge",""],
["rs.htm","Funktionsblockbibliothek &#62; Logik &#62; Getriggerte Operationen &#62; Selbsthalterelais","Selbsthalterelais",""],
["rs_dialog.htm","Dialog","Dialog",""],
["run_mainprogram.htm","Robotino&#174; View benutzen &#62; Das Hauptprogramm ausführen","Das Hauptprogramm ausführen",""],
["run_program.htm","Robotino&#174; View benutzen &#62; Ein Unterprogramm ausführen","Ein Unterprogramm ausführen",""],
["sample_hold.htm","Funktionsblockbibliothek &#62; Logik &#62; Getriggerte Operationen &#62; Abtast-Halte-Glied","Abtast-Halte-Glied",""],
["scope.htm","Funktionsblockbibliothek &#62; Anzeigen &#62; Oszilloskop","Oszilloskop",""],
["scope_dialog.htm","Funktionsblockbibliothek &#62; Anzeigen &#62; Oszilloskop &#62; Dialog","Dialog",""],
["segmenter.htm","Funktionsblockbibliothek &#62; Veraltete Funktionsblöcke &#62; Segmentierer","Segmentierer",""],
["segmentextractor.htm","Funktionsblockbibliothek &#62; Veraltete Funktionsblöcke &#62; Segment Extrahierer","Segment Extrahierer",""],
["statusbar.htm","Statusleiste","Statusleiste",""],
["structure_and_concept_of_the_workspace.htm","Kennenlernen des Arbeitsbereiches &#62; Aufbau und Konzept der Bedienoberfläche","Aufbau und Konzept der Bedienoberfläche",""],
["subprogram_navigation.htm","Robotino&#174; View benutzen &#62; Navigation in Unterprogrammen","Navigation in Unterprogrammen",""],
["subtraction.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Arithmetische Operationen &#62; Subtraktion","Subtraktion",""],
["terminology.htm","Kennenlernen des Arbeitsbereiches &#62; Bezeichnungen","Bezeichnungen",""],
["time.htm","Funktionsblockbibliothek &#62; Generatoren &#62; Zeitbaustein","Zeitbaustein",""],
["toolbar.htm","Kennenlernen des Arbeitsbereiches &#62; Aufbau und Konzept der Bedienoberfläche &#62; Werkzeugleiste","Werkzeugleiste",""],
["transferfunction.htm","Funktionsblockbibliothek &#62; Mathematik &#62; Funktionen &#62; Transferfunktion","Transferfunktion",""],
["tutorial_2.htm","Beispiele &#62; Ablaufprogramme &#62; Tutorial 2","Tutorial 2",""],
["typkonvertierung.htm","Robotino&#174; View benutzen &#62; Typkonvertierung","Typkonvertierung",""],
["updates.htm","Robotino&#174; View benutzen &#62; Updates","Updates",""],
["update_robotino.htm","Robotino&#174; View benutzen &#62; Robotino Pakete aktualisieren","Robotino Pakete aktualisieren",""],
["upload_to_robotino.htm","Robotino&#174; View benutzen &#62; Projekte auf Robotino laden und ausführen","Projekte auf Robotino laden und ausführen",""],
["valuereader.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Werteleser","Werteleser",""],
["valuereader_dialog.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Werteleser &#62; Dialog","Dialog",""],
["valuewriter.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Werteschreiber","Werteschreiber",""],
["valuewriter_dialog.htm","Funktionsblockbibliothek &#62; Datenaustausch &#62; Werteschreiber &#62; Dialog","Dialog",""],
["vectormath_elementoperations.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Elementoperationen","Elementoperationen",""],
["vectormath_transformations.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Transformationen","Transformationen",""],
["vectormath_transformations_rotate_example.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Transformationen &#62; Rotieren &#62; Beispiel","Beispiel",""],
["vectormath_vectoroperations.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Vektoroperationen","Vektoroperationen",""],
["vectormath_vectoroperations_length.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Vektoroperationen &#62; Norm","Norm",""],
["vectormath_vectoroperations_length_example.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Vektoroperationen &#62; Norm &#62; Beispiel","Beispiel",""],
["vector_addition.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Vektoroperationen &#62; Addition","Addition",""],
["vector_addition_dialog.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Vektoroperationen &#62; Addition &#62; Dialog","Dialog",""],
["vector_dot.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Vektoroperationen &#62; Skalarprodukt","Skalarprodukt",""],
["vector_element_addtion.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Elementoperationen &#62; Addition","Addition",""],
["vector_element_division.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Elementoperationen &#62; Division","Division",""],
["vector_element_multiplication.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Elementoperationen &#62; Multiplikation","Multiplikation",""],
["vector_element_subtraction.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Elementoperationen &#62; Subtraktion","Subtraktion",""],
["vector_math.htm","Funktionsblockbibliothek &#62; Vektorrechnung","Vektorrechnung",""],
["vector_rotate.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Transformationen &#62; Rotieren","Rotieren",""],
["vector_subtraction.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Vektoroperationen &#62; Subtraktion","Subtraktion",""],
["vector_subtraction_dialog.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Vektoroperationen &#62; Subtraktion &#62; Dialog","Dialog",""],
["vector_to_cartesian.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Transformationen &#62; Vektor nach Kartesisch","Vektor nach Kartesisch",""],
["vector_to_polar.htm","Funktionsblockbibliothek &#62; Vektorrechnung &#62; Transformationen &#62; Vektor nach Polar","Vektor nach Polar",""],
["welcome.htm","Willkommen","Willkommen",""],
["workspace_tour.htm","Kennenlernen des Arbeitsbereiches","Kennenlernen des Arbeitsbereiches",""],
["xor.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; XOR","XOR",""],
["xor_example.htm","Funktionsblockbibliothek &#62; Logik &#62; Logische Operationen &#62; XOR &#62; Beispiel","Beispiel",""]];
