#ifndef _REC_DATAEXCHANGE_PORTS_H_
#define _REC_DATAEXCHANGE_PORTS_H_

#define REC_DATAEXCHANGE_SERVER_DEFAULT_PORT 9080
#define REC_DATAEXCHANGE_UDP_SERVER_DEFAULT_PORT 9180

#endif //_REC_DATAEXCHANGE_PORTS_H_

