pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["ablaufprogramme.htm","Control programs","Control programs In this chapter a simple control program with alternative branches is realized. ",""],
["abs.htm","Absolute Value","Absolute Value Gives the absolute value of Input. Inputs Type Default Description Input float 0 Outputs Output float abs( Input ) ",""],
["addition.htm","Addition","Addition The Addition function block adds up to 10 summands. See also http://en.wikipedia.org/wiki/Addition . Inputs Type Default Description Summ...",""],
["and.htm","AND","AND The Output of the AND is true only if all Inputs are true. See type conversion how numbers are converted to bool. Inputs Type Default Descript...",""],
["and_dialog.htm","Dialog","Dialog ",""],
["and_example.htm","Example","Example ",""],
["and_fl.htm","AND FL","AND FL The output Q of the AND FL (with edge control) is only set to true if all inputs are true, and if at least one input was false during the p...",""],
["and_fl_dialog.htm","Dialog","Dialog ",""],
["and_fl_example.htm","Example","Example When the output of the generator changes from 0 to 1 the output of the AND FL is true for one cycle. ",""],
["cartesian_to_vector.htm","Cartesian to Vector","Cartesian to Vector Create a vector from its cartesian components. Inputs Type Default Description x float 0 x component. y float 0 y component. O...",""],
["changelog.htm","Improvements","Improvements New in Version 3.0.16: Bug fixes New in Version 3.0.15: Gyroscope New in Version 3.0.13: File format rvwx. XML file compressed with g...",""],
["change_language.htm","Changing language","Changing language Robotino&#174; View automatically recognizes the language set in your Windows&#174; System and selects the corresponding translation of Ro...",""],
["connect_to_robotino.htm","Connect to Robotino&#174;","Connect to Robotino&#174; Enter Robotino&#39;s IP address in the IP address input field in the tool bar . The default address is 172.26.1.1. Click onto the...",""],
["controlpanel.htm","Control Panel","Control Panel A control panel usable with the mouse. Outputs Type Description vx float Velocity in x-direction vy float Velocity in y-direction om...",""],
["controlpanel_dialog.htm","Dialog","Dialog The control panel can be used as follows: By clicking one of the buttons the robot system is moved into the arrow&#39;s direction. By clicking ...",""],
["controlpanel_example.htm","Example","Example ",""],
["counter_down.htm","Counter down","Counter down Counter down is similar to Counter up . The only difference is that the counting value is decremented by 1 if a counting event occurs. ",""],
["counter_down_dialog.htm","Dialog","Dialog See dialog of Counter up . ",""],
["counter_up.htm","Counter up","Counter up The counter counts the number of events at its Input connector Inputs Type Default Description Input bool false Counter input. Counter ...",""],
["counter_up_dialog.htm","Dialog","Dialog Count on rising edge Increment the counter by 1 if the input at time t is false and at time t+1 true. Count on falling edge Increment the c...",""],
["counter_up_example.htm","Example","Example The \" Arbitrary Waveform Generator \" generates a sin waveform with amplitude 2 and frequency 1 Hz. The output of the generator is of type ...",""],
["create_net.htm","Interlink function blocks","Interlink function blocks By connecting output connectors to input connectors of function blocks, data is passed from the function blocks output t...",""],
["custom.htm","Custom","Custom This class contains function blocks that can be programmed by the user himself using the script language Lua. ",""],
["custom_lua.htm","Lua-Skript","Lua script With Lua scripts it is easily possible to do almost any calculations whose realization is impossible or very complex by using the avail...",""],
["custom_lua_dialog.htm","Dialog","Dialog The dialog has three tabs. The first one is used to configure the function block: Here the number of inputs and outputs can be set. Besides...",""],
["custom_lua_example.htm","Beispiel","Beispiel The script in this example reads the values of the inputs 1 and 2 and writes their sum to output 1 and their difference to output 2. The ...",""],
["dataexchange.htm","Data exchange","Data exchange This category contains function blocks for data exchange within Robotino&#174; View or with external applications. ",""],
["demultiplexer.htm","Demultiplexer","Demultiplexer The demultiplexer connects one input to a selectable output. Inputs Type Default Description Control signal int 0 Determines the out...",""],
["demultiplexer_dialog.htm","Dialog","Dialog ",""],
["demultiplexer_example.htm","Example","Example ",""],
["deprecated_functionblocks.htm","Deprecated function blocks","Deprecated function blocks Here you can find function blocks that are not supported any more but that can still be loaded by old programs. In the ...",""],
["devices.htm","Devices","Devices Devices establish the connection between Robotino View and the outside world. The device \"Robotino\" can communicate with real Robotino or ...",""],
["devices_add_and_edit.htm","Add and edit","Add and edit When creating a new project the device \"Robotino\" is automatically added. To add more devices you have to change the current view to ...",""],
["devices_dataexchange.htm","Data exchange","Data exchange Devices from this category are used to exchange data between different Robotino View instances over a network. ",""],
["devices_dataexchange_client.htm","Client","Client The data exchange client connects to a data exchange server . Afterwards data can be exchange with the server using the server&#39;s communicat...",""],
["devices_dataexchange_client_dialog.htm","Dialog","Dialog Server address is the IP address of the server the client wants to connect to. If only the IP address is given the connection is establishe...",""],
["devices_dataexchange_server.htm","Server","Server The data exchange server can be used by an arbitrary number of clients to exchange data over an arbitrary number of communication channels....",""],
["devices_dataexchange_server_dialog.htm","Dialog","Dialog The data exchange server&#39;s dialog is opened by double clicking onto the device symbol in the function block library. Server port is the TCP...",""],
["devices_dataexchange_server_units.htm","Function blocks","Function blocks The function blocks are used to exchange data with the devices. ",""],
["devices_dataexchange_units_reader.htm","Reader","Reader The Reader reads data from a communication channel. Outputs Type Description Value int, float, float array, laser range data The value of t...",""],
["devices_dataexchange_units_writer.htm","Writer","Writer The Writer writes data into a communication channel. Inputs Type Default Description Value int, float, float array, laser range data 0 The ...",""],
["devices_joystick.htm","Joystick","Joystick The device \"Joystick\" allows access to a locally attached joystick. ",""],
["devices_localcamera.htm","Local camera","Local camera The device \"Local camera\" allows access to a camera that is attached to the computer (e.g. a webcam). ",""],
["devices_robotino.htm","Robotino","Robotino The Robotino Device provides access to sensors and actors of the Robotino&#174; robot system. ",""],
["devices_robotino_rangefinder.htm","Laser rangefinder","Laser rangefinder ",""],
["devices_show_dialogs.htm","Show dialogs","Show dialogs Every device has a configuration dialog. This dialog is opened by double clicking the device in the function block library ",""],
["device_robotino_charger_dialog.htm","Charger","Charger The dialog shows the status of charger 1 in Robotino. If Robotino is equipped with NiMH accumulators more than one charger is installed in...",""],
["device_robotino_connection.htm","Connection","Connection Outputs Quality float 0 Displays the connection quality. 0: Poor quality. The connection will break down. 100: Best quality. Connected ...",""],
["device_robotino_gyroscope.htm","Gyroskop","Gyroscope Outputs the readings of Robotino&#39;s internal gyroscope. Ausgänge Typ Einheit Beschreibung Angle float deg (degree) Robotino&#39;s orientation...",""],
["device_robotino_manipulator.htm","Manipulator","Manipulator ",""],
["device_robotino_manipulator_axescount.htm","Anzahl der Achsen","Number of axes Shows the number of axes. Outputs Typ Unit Description Number of axes int Number of axes. See the example how to use the grappler. ",""],
["device_robotino_manipulator_axis.htm","Achse","Axis Sensor readings of one axis. Outputs Typ Unit Default Description Current position float deg Current axis position. Current speed float rpm C...",""],
["device_robotino_manipulator_axis_writer.htm","Achse","Axis Control of a single axis. Inputs Typ Unit Default Description Position set-point float deg 0 Axis position set-point. Speed set-point float d...",""],
["device_robotino_manipulator_dialog.htm","Manipulatordialog","Manipulator dialog This dialog lets you configure Robotino&#39;s optional manipulator. 1 Line 1-3 enabled: Switch the power supply of the servos. In c...",""],
["device_robotino_manipulator_functionblocks_reader.htm","Reader","Reader ",""],
["device_robotino_manipulator_functionblocks_writer.htm","Writer","Writer ",""],
["device_robotino_manipulator_positionselector.htm","Positionsauswahl","Position selector Approach stored positions. Inputs Typ Unit Default Description Index int 0 Number of position to drive to. The first valid numbe...",""],
["device_robotino_manipulator_positionselector_dialog.htm","Dialog","Dialog Specification of the accepted tolerance from the target position. If all axes positions are within the range of tolerances of the target po...",""],
["device_robotino_rangefinder_analysis.htm","Laser rangefinder analysis","Laser rangefinder analysis Analysis of rangedata. Inputs Typ Unit Default Description Data rangedata Measurement data. Angle deg 0 Viewing angle t...",""],
["device_robotino_rangefinder_analysis_dialog.htm","Dialog","Dialog Display of rangefinder measurements. The red cone shows the angular field analysed. The length of the red cone is equal to the minimum leng...",""],
["device_robotino_rangefinder_dialog.htm","Laser rangefinder dialog","Laser rangefinder dialog This dialog shows status information about the optional available laser rangefinder for Robotino. ",""],
["device_robotino_rangefinder_functionblocks.htm","Funktionsblöcke","Funktionsblöcke Geben Sie hier den Text ein. ",""],
["device_robotino_rangefinder_information.htm","Laser rangefinder info","Laser rangefinder info Rangefinder information Ausgänge Typ Einheit Beschreibung Sequence number int Is incremented by 1 with every measurement re...",""],
["device_robotino_rangefinder_rangefinder.htm","Laser rangefinder","Laser rangefinder Output of laser rangefinder data. Outputs Typ Default Description Laser rangefinder data rangedata Measurement data. ",""],
["device_robotino_robotino_xt.htm","Robotino XT","Robotino XT see http://www.festo.com/cms/en_corp/11367.htm ",""],
["device_robotino_robotino_xt_actors.htm","Actors","Actors The compact version of the bionic handling assistant is driven by eight bellows plus gripper. Robotino View allows to set the pressure in e...",""],
["device_robotino_robotino_xt_actors_bellows.htm","Bellows","Bellows Set the pressure set-point for the corresponding bellows. Inputs Typ Unit Default Description Pressure float bar 0 Pressure set-point see ...",""],
["device_robotino_robotino_xt_actors_gripper_open.htm","Gripper open / close","Gripper open / close Inputs Type Unit Default Description Open bool falsch If true, the gripper will be opened. Close bool falsch If true and \"Ope...",""],
["device_robotino_robotino_xt_actors_gripper_rotate.htm","Gripper rotate","Gripper rotate Calculate pressure for bellows 7 and 8 from direction of rotation. Inputs Typ Unit Default Description Rotate int 0 If 0, rotate cl...",""],
["device_robotino_robotino_xt_actors_gripper_rotate_example.htm","Beispiel","Beispiel ",""],
["device_robotino_robotino_xt_actors_segment_xy.htm","Segment XY","Segment XY Calculate pressures for three bellows from xy-coordinates. Inputs Typ Unit Default Description x float 0 x-displacement. Range [-1;1] y...",""],
["device_robotino_robotino_xt_actors_segment_xy_example.htm","Beispiel","Beispiel ",""],
["device_robotino_robotino_xt_dialog.htm","Robotino XT","Robotino XT The dialog shows status information about Robotino XT. ",""],
["device_robotino_robotino_xt_io.htm","I/O","I/O Several other sensors and actors are attached to the inputs and outputs of the control board: The string potentiometers and the foil potentiom...",""],
["device_robotino_robotino_xt_io_compressors.htm","Compressors","Compressors Turns the compressors on or off. If the compressors are activated, they will only run until the maximum pressure has been reached. The...",""],
["device_robotino_robotino_xt_io_foilpot.htm","Foil potentiometer","Foil potentiometer Shows the voltage value of the foil potentiometer.2 Outputs Type Default Description Value float 0 Voltage on the Potentiometer. ",""],
["device_robotino_robotino_xt_io_gripper_valve.htm","Gripper valve","Gripper valve Controls the respective gripper valve. Inputs Type Default Description Value bool false Controls the respective valve. Controlling t...",""],
["device_robotino_robotino_xt_io_pressuresensor.htm","Pressure sensor","Pressure sensor Returns true if the maximum pressure has been reached. Outputs Type Default Description Value bool false true if the maximum press...",""],
["device_robotino_robotino_xt_io_stringpots.htm","String potentiometers","String potentiometers Shows the voltage values of the string potentiometers. Outputs Type Default Description Pot #1 value float 0 Voltage on pote...",""],
["device_robotino_robotino_xt_io_waterdrainvalve.htm","Water drain valve","Water drain valve Opens the water drain valve to remove water from the system. Inputs Type Default Description value bool false Opens the valve. ",""],
["device_robotino_robotino_xt_sensors.htm","Sensoren","Sensoren There are pressure sensors for each bellows. ",""],
["device_robotino_robotino_xt_sensors_bellows.htm","Bellows","Bellows Shows the pressure inside the corresponding bellows. Outputs Typ Unit Default Description Pressure float bar 0 Pressure inside the bellows...",""],
["device_udp_dataexchange.htm","UDP data exchange","UDP data exchange With the UDP data exchange device data can be exchanged between Robotino View and external applications via UDP. ",""],
["device_udp_dataexchange_checksum.htm","Checksum","Checksum If the message is shorter than 100 byte, the sum s0 will be calculated from the whole package&#39;s single bytes. If the message contains 100...",""],
["device_udp_dataexchange_dialog.htm","Dialog","Dialog The dialog of the UDP data exchange device can be opened by double-clicking on the device entry in the function block library. In the dialo...",""],
["device_udp_dataexchange_example.htm","Example","Example ",""],
["device_udp_dataexchange_functionblocks.htm","Function blocks","Function blocks The function blocks are used to exchange data with the devices. ",""],
["device_udp_dataexchange_functionblocks_message0.htm","Message 0","Message 0 The function blocks in category Message 0 allow sending and receiving data. ",""],
["device_udp_dataexchange_functionblocks_message0_input.htm","Input","Input The inputs of message 0 provide received values. ",""],
["device_udp_dataexchange_functionblocks_message0_input_reader.htm","Reader","Reader The reader reads data and outputs received data. There is a reader for each of INT0 to INT7. Outputs Type Description Value int The receive...",""],
["device_udp_dataexchange_functionblocks_message0_input_writer.htm","Writer","Writer The writer takes the data to send and passes them to the device to send it to the receivers via UDP. There is a writer for each of INT0 to ...",""],
["device_udp_dataexchange_functionblocks_message0_output.htm","Output","Output The outputs are used to send values. ",""],
["device_udp_dataexchange_functionblocks_message1.htm","Message 1","Message 1 Message 1 is identical to Message 0 . ",""],
["device_udp_dataexchange_protocol.htm","Protocol","Protocol Specification of the data structure Byte Function 0 Message ID 1-2 Number of Bytes of the whole message N. Type is UINT16 3 Checksum (to ...",""],
["device_udp_dataexchange_protocol_0.htm","Message 0","Message 0 Byte Function 0 0 1 36 2 0 3 Checksum 4-7 INT0 of type INT32 8-11 INT1 of type INT32 12-15 INT2 of type INT32 16-19 INT3 of type INT32 2...",""],
["device_udp_dataexchange_protocol_1.htm","Message 1","Message 1 Byte Function 0 1 1 36 2 0 3 Checksum 4-7 INT0 of type INT32 8-11 INT1 of type INT32 12-15 INT2 of type INT32 16-19 INT3 of type INT32 2...",""],
["device_udp_dataexchange_types.htm","Data types","Data types Type Width in bytes Description UINT16 2 Byte0: low Byte1: high On a little endian system a UINT16 data value can be copied directly in...",""],
["display.htm","Display","Display This category contains the function blocks for the visualization of data. ",""],
["division.htm","Division","Division Calculates the quotienten from dividend and divisor. See http://en.wikipedia.org/wiki/Division_(mathematics) . Inputs Type Default Descri...",""],
["equal.htm","Equal","Equal The output is true, if the absolute value of Input1 - Input2 is less epsilon, with epsilon = 0.0000002384185792 Inputs Type Default Descript...",""],
["examples_logic.htm","Logic","Logic In this chapter well-known electrical circuits are realized with logical modules. ",""],
["examples_logic_flipflop.htm","FlipFlop","FlipFlop ",""],
["examples_logic_multiplexer.htm","Multiplexer","Multiplexer ",""],
["example_array.htm","Arrays","Arrays The Float array composer creates the array 0.1 0.6 Not connected inputs are ignored in the final array. The Float array splitter maps the a...",""],
["example_colortracker.htm","Color tracker","Color tracker The following example shows how a combination of color range finder , Maximum-Filter and Segment tracker can be used to align Roboti...",""],
["example_colortracker_camera.htm","Camera","Camera Robotino&#39;s Camera provided the sensory input. back to example ",""],
["example_colortracker_colorrangefinder.htm","Color range finder","Color range finder Within the dialog of the color range finder a work piece is selected so that the range of colors the image is searched for is t...",""],
["example_colortracker_drivesystem.htm","Drive system","Drive system The control points are given to the Omni drive and then to Robotino&#39;s Motors . back to example ",""],
["example_colortracker_filter.htm","Filter","Filter The Maximum-Filter increases white areas so that there are connected areas for each work piece even in the case of varied illumination cond...",""],
["example_colortracker_rotation.htm","Calculation of rotation","Calculation of rotation By Subtraction of the x-coordinate of work piece (b) from the x-coordinate of work piece (a) we get the x-distance of the ...",""],
["example_colortracker_segmenttracker1.htm","Segment tracker 1","Segment tracker 1 The first Segment tracker tracks the segment which is nearest to the image bottom border at program start. back to example ",""],
["example_colortracker_segmenttracker2.htm","Segment tracker 2","Segment tracker 2 The second Segment tracker tracks the second work piece. back to example ",""],
["example_colortracker_ymovement.htm","Calculation of y-movement","Calculation of y-movement The Image information gives the height and width of the image. The width is used to calculate the distance of work piece...",""],
["example_grappler.htm","Grappler for Robotino&#174;","Grappler for Robotino&#174; The picture shows the Grappler for Robotino&#174;. The grappler is made of four axes (A1 to A4). With the push buttons B1 and B2...",""],
["example_imageprocessing.htm","Image processing","Image processing ",""],
["example_imageprocessing_search_and_approch.htm","Search and approach","Search and approach This example describes a program which allows Robotino to search for a colored object and drive to it. The program consists of...",""],
["example_imageprocessing_search_and_approch_approach.htm","Anfahren","Anfahren 1. Calculation of the forward speed set-point 2. Evaluation of the break condition The image processing and the calculation of the rotati...",""],
["example_imageprocessing_search_and_approch_approch_setpoint.htm","Set-point (1)","Set-point (1) The basis for the calculation of the forward speed set-point in mm/s is the area of the red cylinder in pixel emitted by the Segment...",""],
["example_imageprocessing_search_and_approch_approch_termination.htm","Break condition (2)","Break condition (2) The sub program is terminated when the forward speed set-point is 0. ",""],
["example_imageprocessing_search_and_approch_rotate.htm","Anfahren","Rotate 1. Image processing 2. Calculation of the rotation speed set-point 3. Evaluation of the break condition ",""],
["example_imageprocessing_search_and_approch_rotate_imageprocessing.htm","Image processing (1)","Image processing (1) The Color range finder is used to extract the colored object from the camera image (in this example the colored object is a r...",""],
["example_imageprocessing_search_and_approch_rotate_setpoint.htm","Set-point (2)","Set-point (2) The set-point for the rotational speed is calculated by half image width minus the x-coordinates of the red cylinder. The Transferfu...",""],
["example_imageprocessing_search_and_approch_rotate_termination.htm","Breack condition (3)","Breack condition (3) The sub program is terminated when the global variable \"next\" is unequal to 0. If the speed set-point is 0 the red cylinder i...",""],
["filter.htm","Filter","Filter This category contains function blocks for filtering and smoothing of signals. ",""],
["filter_mean.htm","Mean filter","Mean filter Calculates the mean of the input value for up to 1000 steps. Inputs Type Default Description Input float 0 Input signal Outputs Output...",""],
["filter_mean_dialog.htm","Dialog","Dialog Depth is the number of previous time steps which are taken to calculate the mean value. ",""],
["float_array_composer.htm","Float array composer","Float array composer The Float array composer creates a float array from up to 10 float values or arrays. For the type conversion from float value...",""],
["float_array_composer_dialog.htm","Dialog","Dialog Here you can set the number of inputs of this function block. ",""],
["float_array_decomposer.htm","Float array decomposer","Float array decomposer The Float array decomposer extracts a sub array from a float array. Inputs Type Default Description Array float array empty...",""],
["float_array_index_access.htm","Float array index access","Float array index access The index access module allows access to the single values of a float array. Inputs Type Default Description Array float ...",""],
["float_array_splitter.htm","Float array splitter","Float array splitter Splits an array to outputs. Eingänge Typ Standard Beschreibung Array float array empty array Float array Ausgänge Index 1 flo...",""],
["float_array_splitter_dialog.htm","Dialog","Dialog Here you can set the number of outputs of this function block. ",""],
["float_array_splitter_example.htm","Beispiel","Example see examples/Arrays ",""],
["functionblocklibrary.htm","Function block library","Function block library The folder function block library contains function blocks that are available in every project. Currently visible are the f...",""],
["function_block_library.htm","Function block library","Function block library The control programs created with Robotino&#174; View consist of interlinked function blocks. These are located in the function ...",""],
["generator.htm","Generators","Generators This category contains numerous function blocks to create signals. ",""],
["generators_arbitrary.htm","Arbitrary waveform generator","Arbitrary waveform generator Generation of adjustable waveforms. See also http://en.wikipedia.org/wiki/Arbitrary_waveform_generator . Inputs Type ...",""],
["generators_arbitrary_dialog.htm","Dialog","Dialog The upper part of the dialog is similar to the dialog known from the Transfer Function . In addition the Arbitrary wavefrom generator has t...",""],
["generators_arbitrary_example.htm","Example","Example Robotino&#39;s Motor 1 rotates driven by a sine waveform. ",""],
["generators_constant.htm","Constant","Constant Generation of a constant value. The type of the constant and also the graphical display changes with the type of the connected input conn...",""],
["generators_random.htm","Random generator","Random generator The random generator creates random numbers within a specific range. Inputs Type Default Description Maximum float 1 Upper bound ...",""],
["generators_timer_example.htm","Example","Example Timer and Transfer Function generate a puls of amplitude 10 1s after program start. ",""],
["getting_started.htm","Using Robotino&#174; View","Using Robotino&#174; View Robotino&#174; View is used to create the control programs for Robotino&#174;. In this section you will learn how to: create a new proj...",""],
["globalvariables.htm","Variables","Variables Global variables are a kind of special. For all global variables there are function blocks for reading and writing available in every su...",""],
["globalvariables_general.htm","Global variables","Global variables Global variables can be read and written in every subprobram of a project; in the main program they can be used in the transition...",""],
["greater.htm","Greater","Greater The Output is true, if Input1 is greater Input2. Inputs Type Default Description Input 1 float 0 Input 2 float 0 Outputs Output bool \"Inpu...",""],
["greater_equal.htm","Greater equal","Greater equal The Output is true, if Input1 is greater equal Input2. Inputs Type Default Description Input 1 float 0 Input 2 float 0 Outputs Outpu...",""],
["hsv_colorspace.htm","HSV color space","HSV color space Source: http://en.wikipedia.org/wiki/File:HSV_color_solid_cylinder_alpha_lowgamma.png In contrast to the RGB color space which def...",""],
["imageprocessing.htm","Image processing","Image processing This category contains function blocks for image processing. ",""],
["imageprocessing_calibration.htm","Calibration","Calibration This function block performs a camera calibration. Inputs Type Default Description Input image Input image. Outputs Output image Image...",""],
["imageprocessing_calibration_dialog.htm","Dialog_2","Dialog ",""],
["imageprocessing_calibration_example.htm","Beispiel","Beispiel ",""],
["imageprocessing_colorrangefinder.htm","Color range finder","Color range finder Pixel with color within the selected color range are set white. All other pixels are set black. Inputs Type Default Description...",""],
["imageprocessing_colorrangefinder_dialog.htm","Dialog","Dialog If \"Show result\" is not set the input image is shown (1). Within the input image you can mark an area by clicking and dragging with the mou...",""],
["imageprocessing_colorrangefinder_example.htm","Beispiel","Example see example/Color tracker ",""],
["imageprocessing_colorspace_conversion.htm","Colorspace conversion","Colorspace conversion Inputs Type Default Description Input image Input image Outputs Output image Converted image ",""],
["imageprocessing_colorspace_conversion_dialog.htm","Dialog","Dialog In the colorspace conversion dialog the target color space can be selected. ",""],
["imageprocessing_filter.htm","Filter","Filter Different filter algorithms for color and greyscale images. Inputs Type Default Description Input image Input image Outputs Output image Fi...",""],
["imageprocessing_filter_dialog.htm","Dialog","Dialog Filter: Select the filter Maximum: Set the color of the current pixel to the maximum from all pixels within the mask. The output image shri...",""],
["imageprocessing_filter_example.htm","Example","Example see example/Color tracker Example for Maximum-Filter: Mask size=3, Input image (7x5), Output image (5x3) 1 2 3 4 5 6 7 1 2 3 4 5 6 7 2 3 4...",""],
["imageprocessing_imageinfo.htm","Image Information","Image Information Get the width and height of the input image. Inputs Type Default Description Input image Input image Outputs Width int Image wid...",""],
["imageprocessing_imageinfo_dialog.htm","Dialog","Dialog The dialog shows the input image. ",""],
["imageprocessing_imageinfo_example.htm","Example","Example The images of the test sequence generated by the image reader have a resolution of 320 x 240 Pixel. ",""],
["imageprocessing_linedetector_dialog.htm","Dialog","Dialog The area which is search for a line is marked by the horizontal red lines. The bottom line marks the \"Search start\". The top line marks \"Se...",""],
["imageprocessing_linedetector_example.htm","Example","Example The image from Robotino&#39;s camera (here from the Robotino Simulator) is used as input for the line detector. We use the Image Information f...",""],
["imageprocessing_marker_detection.htm","Filter_4","Marker detection This function block detects markers in an image, Inputs Type Default Description Image image Input image. Outputs Output image Im...",""],
["imageprocessing_marker_detection_dialog.htm","Dialog_4","Dialog ",""],
["imageprocessing_marker_position.htm","Filter_3","Marker position Given a marker ID this function block outputs the marker position relative to the camera. Inputs Type Default Description Image im...",""],
["imageprocessing_marker_position_dialog.htm","Dialog","Dialog ",""],
["imageprocessing_marker_position_example.htm","Beispiel","Beispiel ",""],
["imageprocessing_roi.htm","ROI","ROI Select an interesting region inside the input image (Region Of Interest, ROI). Inputs Type Default Description Input image Input image Outputs...",""],
["imageprocessing_roi_dialog.htm","Dialog","Dialog The region of interest can be marked with the mouse. ",""],
["imageprocessing_roi_example.htm","Example","Example The Image reader generates a test sequence of images. The bottom Line Detector uses the whole image while the upper Line Detector searches...",""],
["imageprocessing_segmenter_dialog.htm","Dialog","Dialog Button/Display Description 0 Display of the input image and of segments found 1 When checked the input image is displayed 2 When checked fo...",""],
["imageprocessing_segmenter_example.htm","Example","Example The image reader operates in test mode and generates a sequence of test images. The segmenter searches for connected regions within the in...",""],
["imageprocessing_segmentextractor_dialog.htm","Dialog","Dialog Selected segment The spinbox is editable if the input connector \"Selected segment\" is not connected. The segment number to search for. Mini...",""],
["imageprocessing_segmentextractor_example.htm","Example","Example The image reader creates a test sequence with three colored squares. The segmenter searches the image for red, green and blue regions. The...",""],
["imageprocessing_segmenttracker.htm","Segment tracker","Segment tracker Find closed segments in a greyscale image and track an initially chosen segment. To track all segments within an image multiple Se...",""],
["imageprocessing_sgmenttracker_dialog.htm","Dialog","Dialog Initialization: The method by which the to be tracked segment is chosen. The initialization is done at program start and if the Restart inp...",""],
["imageprocessing_sgmenttracker_example.htm","Beispiel","Example see example/Color tracker ",""],
["imagereader.htm","Bildleser","Image Reader The image reader reads single image files from the file system. Path and prefix can be set in the dialog . Supported image file forma...",""],
["imagereader_dialog.htm","Dialog","Dialog From top: Visualization of the current image Prefix: Constraint when searching for images with suffix \".bmp\", \".png\", \".jpg\" und \".jpeg\". D...",""],
["imagereader_example.htm","Beispiel","Example The first step is to specify the directory where to look for images. If no prefix is given all images with suffix \".bmp\", \".png\", \".jpg\" a...",""],
["imagewriter.htm","Image Writer","Image Writer The image writer writes a sequence of JPEG images to the file system. Path and prefix can be specified in the dialog . The image&#39;s nu...",""],
["imagewriter_dialog.htm","Dialog","Dialog From top to bottom: Directory: The directory into which the image files are written. Prefix: The first part of the image file name. The com...",""],
["imagewriter_example.htm","Example","Example See example image reader . ",""],
["inputdevices.htm","Input Devices","Input Devices This category supplies the function blocks for realizing the interaction with the user. ",""],
["inputdevices_slider.htm","Slider","Slider The slider creates any integer value within a specified range. ",""],
["inputdevices_slider_dialog.htm","Dialog","Dialog In the dialog the slider&#39;s range and orientation (1 = horizontal, 0 = vertical) can be adjusted. ",""],
["insert_functionblocks.htm","Insert function blocks","Insert function blocks into sub-programs After creating a new project or after loading an existing project from file you can start developing your...",""],
["install_update_uninstall.htm","Installation, update and de-installation","Installation, update and de-installation You must be in possession of the administrator rights to be able to install Robotino&#174; View. To install Ro...",""],
["joystick_axis.htm","Axis","Axis Read the position of a joystick&#39;s axis. Outputs Type Description Value int Range -1000 to 1000. ",""],
["joystick_button.htm","Button","Button Reads the state of a joystick&#39;s button. Outputs Type Description Value bool True if the button is pressed, false otherwise. ",""],
["joystick_dialog.htm","Dialog","Dialog 1 List of available joysticks The combo box contains an entry for every joystick available at this computer. This list is updated whenever ...",""],
["joystick_functionblocks.htm","Function blocks","Function blocks Function blocks to read button and axis states. ",""],
["keyboard_layout.htm","Keyboard shortcuts","Keyboard shortcuts Function Keyboard shortcut Open file Ctrl + O Save file Ctrl + S Save file as Shift + Ctrl + S Quit Robotino&#174; View Ctrl + Q Und...",""],
["laserrangefinder_data_display.htm","Laser range finder data display","Laser range finder data display The Laser range finder data displays the data from a optional laser-scanner Input Typ Description Data laser range...",""],
["laserrangefinder_data_display_dialog.htm","Dialog","Dialog ",""],
["legal_notice.htm","Legal notice","Legal notice This work partially bases on, distributes or contains work of third parties, which are listed in the following. Distribution of this ...",""],
["less.htm","Less","Less The Output is true, if Input1 is less Input2. Inputs Type Default Description Input 1 float 0 Input 2 float 0 Outputs Output bool \"Input1\" le...",""],
["less_equal.htm","Less equal","Less equal The Output is true, if Input1 is less equal Input2. Inputs Type Default Description Input 1 float 0 Input 2 float 0 Outputs Output bool...",""],
["linedetector.htm","Line Detector","Line Detector Searches for a line in the input image. Inputs Type Default Description Input image Input image Threshold int 0 The threshold is def...",""],
["load_state.htm","Load an existing project","Load an existing project There are three possibilities to load an existing project: Via the menu bar File Open Via the tool bar with the button \"L...",""],
["localcamera_camera.htm","Camera","Camera Live image of the local camera. Inputs Type Default Description Outputs Image image Live image Color depth and resolution can be selected i...",""],
["localcamera_camera_dialog.htm","Dialog","Dialog The camera dialog shows the current image. To adjust the image resolution see device dialog . ",""],
["localcamera_dialog.htm","Dialog","Dialog 1 List of available cameras All cameras attached to the system are shown here. The list is updated when a new camera is attached to or remo...",""],
["localcamera_functionblocks.htm","Function blocks","Function blocks The function blocks allow to use the device \"Local camera\" in a sub-program. ",""],
["logic.htm","Logic","Logic The Logic category contains components as recognized from the electronic logic modules. ",""],
["logic_bitwise.htm","Bitwise operations","Bitwise operations ",""],
["logic_bitwise_and.htm","Bitwise And","Bitwise And This function block calculates the bitwise conjunction of two integer values. Only the bits that are 1 in both operands are 1 in the r...",""],
["logic_bitwise_and_example.htm","Beispiel","Example Value Binary representation Operand 1 12 1100 Operand 2 6 0110 Result 4 0100 ",""],
["logic_bitwise_leftshift.htm","Bitwise Shift Left","Bitwise Shift Left This function block performs a left arithmetic bit shift on the input. Inputs Type Default Description Input int 0 Shift int 0 ...",""],
["logic_bitwise_leftshift_example.htm","Beispiel","Example The input is left-shifted by 2. Value Binary representation Input 6 00110 Result 24 11000 ",""],
["logic_bitwise_not.htm","Bitwise Not","Bitwise Not This function block performs a bitwise negation of an integer value. Inputs Type Default Description Operand int 0 Oututs Result int R...",""],
["logic_bitwise_not_example.htm","Beispiel","Example Value Binary representation Operand 6 00110 Result -7 11001 As the calculation is performed with signed value, the most significant bis is...",""],
["logic_bitwise_or.htm","Bitwise Or","Bitwise Or This function block calculates the bitwise disjunction of two integer values. All bits that are 1 in at least one of the operands are a...",""],
["logic_bitwise_or_example.htm","Beispiel","Example Value Binary representation Operand 1 12 1100 Operand 2 6 0110 Result 14 1110 ",""],
["logic_bitwise_rightshift.htm","Bitwise Shift Right","Bitwise Shift Right This function block performs a right arithmetic bit shift on the input. Inputs Type Default Description Input int 0 Shift int ...",""],
["logic_bitwise_rightshift_example.htm","Beispiel","Example The input is right-shifted by 2. Value Binary representation Input 12 1100 Result 3 0011 ",""],
["logic_bitwise_test.htm","Bitwise Test","Bitwise Test This function block tests if a single bit of the input is 1. Inputs Type Default Description Input int 0 Bit int 0 Bit to test in the...",""],
["logic_bitwise_test_example.htm","Beispiel","Example ",""],
["logic_bitwise_xor.htm","Bitwise Exclusive Or","Bitwise Exclusive Or This function block performs the bitwise XOR operation on two integer values. Only bits which are 1 in exactly one operand ar...",""],
["logic_bitwise_xor_example.htm","Beispiel","Example Value Binary representation Operand 1 12 1100 Operand 2 6 0110 Result 10 1010 ",""],
["logic_ops.htm","Logic operations","Logic operations ",""],
["logic_triggered.htm","Triggered operations","Triggered operations ",""],
["math.htm","Mathematics","Mathematics This category contains simple mathematical operations. ",""],
["math_arithops.htm","Arithmetic operations","Arithmetic operations ",""],
["math_arithops_sub_dialog.htm","Dialog","Dialog ",""],
["math_arithpos_addition_dialog.htm","Dialog","Dialog ",""],
["math_arithpos_mult_dialog.htm","Dialog","Dialog ",""],
["math_arrays.htm","Arrays","Arrays ",""],
["math_compops.htm","Comparison Operations","Comparison Operations ",""],
["math_func.htm","Functions","Functions ",""],
["math_funcs_scale.htm","Scale","Scale Easy scaling of values. Inputs Type Default Description x float 0 Outputs y float see Dialog ",""],
["math_func_max_dialog.htm","Dialog","Dialog ",""],
["math_func_min_dialog.htm","Dialog","Dialog ",""],
["math_func_scale_dialog.htm","Dialog","Dialog Choose a function from the combo box. The default function is the identity mapping. Depending on the function selected the parameters are e...",""],
["math_func_transfer_dialog.htm","Dialog","Dialog With the dialog of the Transfer function function block it is possible to define interpolation points for the mapping y(x). The default int...",""],
["math_func_transfer_example.htm","Example","Example The Counter up is incremented every simulation step. The counting value is restricted to the range [0,10]. The Transferfunction defines a ...",""],
["maximum.htm","Maximum","Maximum The value of the output is the maximal value from all inputs. Inputs Type Default Description Input 1 float -1e+037 ... Input 10 float -1e...",""],
["minimum.htm","Minimum","Minimum The value of the output is the minimal value from all inputs. Inputs Type Default Description Input 1 float 1e+037 ... Input 10 float 1e+0...",""],
["modulo.htm","Modulo","Modulo In mathematics, modular arithmetic (sometimes called clock arithmetic) is a system of arithmetic for integers, where numbers \"wrap around\" ...",""],
["multiplexer.htm","Multiplexer","Multiplexer The Multiplexer connects its output to a selectable input. Inputs Type Default Description Control signal int 0 Determines the input t...",""],
["multiplexer_dialog.htm","Dialog","Dialog ",""],
["multiplexer_example.htm","Example","Example see also Examples}Logic} Multiplexer ",""],
["multiplication.htm","Multiplication","Multiplication The Multiplication function block multiplies floating point numbers. See also http://en.wikipedia.org/wiki/Multiplication . Inputs ...",""],
["nand.htm","NAND","NAND The Output of the NAND is false only if all Inputs are true. See type conversion how numbers are converted to bool. Inputs Type Default Descr...",""],
["nand_dialog.htm","Dialog","Dialog ",""],
["nand_example.htm","Example","Example see Example}Logic} FlipFlop ",""],
["nand_fl.htm","NAND_FL","NAND FL The output Q of the NAND with edge control is only set to true if at least one input is false, and if all inputs were true during the prev...",""],
["nand_fl_dialog.htm","Dialog","Dialog ",""],
["navigation.htm","Navigation","Navigation This category comprises function blocks used for navigation. ",""],
["navigation_constant_pose.htm","Constant pose","Constant pose In the input box the pose is specified. Coordinates are separated by spaces characters. Input Resulting pose x y phi (x, y, phi) x y...",""],
["navigation_obstacle_avoidance.htm","Obstacle avoidance","Obstacle avoidance The module Obstacle avoidance calculates a detour for a path round a circular obstacle. Inputs Type Unit Default Description Pa...",""],
["navigation_obstacle_avoidance_dialog.htm","Dialog","Dialog The dialog shows the original path, the obstacle and the detour. ",""],
["navigation_path_composer.htm","Path composer","Path composer Inputs Type Default Description Path 1 path empty path The first sub-path. A single Pose will also be accepted because pose is conve...",""],
["navigation_path_composer_dialog.htm","Dialog","Dialog ",""],
["navigation_path_configuration_dialog1.htm","Configuration dialog 1","Configuration dialog 1 Top left Correlation between angular velocity and angular error dφ. Top right Correlation between forward velocity and angu...",""],
["navigation_path_configuration_dialog2.htm","Configuration dialog 2","Configuration dialog 2 Top left Correlation between the robot&#39;s distance to the virtual way point and the angle to the next path segment. Top righ...",""],
["navigation_path_configuration_dialog3.htm","Configuration dialog 3","Configuration dialog 3 Top Adaption of the coupling factor between the velocity calculated due to the configuration in dialogs 1 and 2 and the rea...",""],
["navigation_path_decomposer.htm","Path decomposer","Path decomposer Cuts a subpath out of a path. A path consists of a list of poses. Index Pose 1 p1 2 p2 ... N pN The inputs Start and Length specif...",""],
["navigation_path_driver.htm","Path driver","Path driver With the path driver it is possible to drive along paths. From the path and the actual pose the velocity and the angular velocity are ...",""],
["navigation_path_driver_example.htm","Example","Example ",""],
["navigation_path_driver_strategy.htm","Strategy","Strategy The path driver function block creates a path which first connects the way points straight-lined. The robot is driven with a virtual way ...",""],
["navigation_path_path_dialog.htm","Path view","Path view ",""],
["navigation_pose_composer.htm","Pose composer","Pose composer Inputs Typ Unit Default Description x float 0 The pose&#39;s x component. y float 0 The pose&#39;s y component. phi float degrees 0 The pose...",""],
["navigation_pose_composer_dialog.htm","Dialog","Dialog Valid pose Specifies if the pose is valid. Invalid poses will be ignored in paths. Orientation Specifies if the orientation is valid and it...",""],
["navigation_pose_decomposer.htm","Pose decomposer","Pose decomposer Inputs Type Unit Default Description Pose pose (0, 0, 0) Pose to decompose. Outputs x float 0 The pose&#39;s x component. y float 0 Th...",""],
["navigation_pose_decomposer_dialog.htm","Dialog","Dialog ",""],
["navigation_positiondriver.htm","Position Driver","Position Driver The position driver is used to drive Robotino to a given position. The position driver generates velocity and angular velocity set...",""],
["new_state.htm","Create a new project","Create a new project There are two possibilities to create a new project: Via the menu bar File New Via the tool bar with the button Create a new ...",""],
["nor.htm","NOR","NOR The NOR&#39;s Output Q is true if all inputs are false. See type conversion how numbers are converted to bool. Inputs Type Default Description Inp...",""],
["nor_dialog.htm","Dialog","Dialog ",""],
["nor_example.htm","Example","Example ",""],
["not.htm","NOT","NOT The Output of the NOT is true if the input is false. See type conversion how numbers are converted to bool. Inputs Type Default Description In...",""],
["not_dialog.htm","Dialog","Dialog Enter topic text here. ",""],
["not_equal.htm","Inequal","Inequal The output is true, if the absolute value of Input1 - Input2 is greater equal epsilon, with epsilon = 0.0000002384185792. Inputs Type Defa...",""],
["not_example.htm","Example","Example The example shows a especialness of the NOT function block. Input and output values are not shown next to its input or output connector. T...",""],
["omnidrive_dialog.htm","Dialog","Dialog ",""],
["omnidrive_inv_dialog.htm","Dialog","Dialog ",""],
["opcclient.htm","OPC Client","OPC Client OPC is a Defaultised interface between different software applications and drivers of different hardware modules (e.g. PLC). Multiple O...",""],
["opcclient_analoginput.htm","Analog Input","Analog Input Reading of the \"Tag\" mapped to AI_Port_x with x in [1;4] Outputs Type Description Value int Range 0 to 65535 ",""],
["opcclient_analogoutput.htm","Analog Output","Analog Output Write Value to the \"Tag\" mapped to AO_Port_x with x in [1;4] Inputs Type Description Value int Range 0 to 65535 ",""],
["opcclient_dialog.htm","Dialog","Dialog 1 Select OPC server The combocox lists all available local OPC servers. 2 Connect Establish a connection to the selected OPC server. 3 Scan...",""],
["opcclient_digitalinput.htm","Digital Input","Digital Input Read bit values of the \"Tag\" mapped to DI_Port_x with x in [1;4] Outputs Type Description Bit 0 bool True if bit 0 is set. ... Bit 7...",""],
["opcclient_digitaloutput.htm","Digital Output","Digital Output Set bits of \"Tag\" mapped to DO_Port_x with x in [1;4] Inputs Type Description Bit 0 bool If true the value send to the OPC server i...",""],
["opcclient_functionblocks.htm","Function blocks","Function blocks Function blocks allow use of the \"OPC Client\" device in a sub-program. ",""],
["opcclient_inputs.htm","Inputs","Inputs ",""],
["opcclient_outputs.htm","Outputs","Outputs ",""],
["or.htm","OR","OR The Output of the OR is true only if at least one Input is true. See type conversion how numbers are converted to bool. Inputs Type Default Des...",""],
["or_dialog.htm","Dialog","Dialog ",""],
["or_example.htm","Example","Example ",""],
["polar_to_vector.htm","Polar to Vector","Polar to Vector Create a vector from its length and orientation. Inputs Type Default Description Length float 0 Length (norm) of the Vector. Phi f...",""],
["positiondriver_dialog.htm","Dialog","Dialog The dialog is split into three parts. The upper part reflects the mapping from distance to the target position d (in mm) to the driving vel...",""],
["positiondriver_example.htm","Example","Example ",""],
["positiondriver_movements.htm","Movements","Movements Four different kinds of movements are possible. Two of them are applicable for holonomic and nonholonomic vehicles each. As Robotino has...",""],
["programming.htm","Programming","Programming To compile function blocks and devices the Robotino&#174; View API is necessary. ",""],
["programming_myfunctionblocks.htm","My function blocks","My function blocks You can find the following examples in %USERPROFILE%\\Festo\\RobotinoView3\\units\\MyFunctionsBlocks. The environment variable %USE...",""],
["programming_myfunctionblocks_newblock.htm","Creating a new function block","Creating a new function block To create a new function block the tool \"Function blick manager\" is included in the Robotino&#174; View API. It can be la...",""],
["programming_myfunctionblocks_preparation.htm","Preparing the build environment","Preparing the build environment To compile a function blick every newer version of Microsoft Visual C++ can be used. It is even possible to use th...",""],
["programming_myfunctionblocks_robotino.htm","Use on Robotino","Use on Robotino It is also possible to use your own function blocks on Robotino. To do this it is necessary to build the plugins for the Linux sys...",""],
["robotino_analoginput.htm","Analog Input","Analog Input Reads the value of an analog input. Outputs Type Unit Description Value float Volt The measured voltage. Range [0;10]. The connector ...",""],
["robotino_battery.htm","Batterie","Batterie Das Stromüberwachungsmodul für Robotino. Eingänge Typ Einheit Standard Beschreibung Ausgänge Externe Stromversorgung bool false Wahr wenn...",""],
["robotino_battery_example.htm","Beispiel","Beispiel ",""],
["robotino_bumper.htm","Bumper","Bumper A tactile sensor is integrated into the bumper. If contacted, the sensor supplies an output signal. Inputs Type Default Description Outputs...",""],
["robotino_camera.htm","Camera","Camera The live image of Robotino&#39;s camera. Inputs Type Default Description Outputs Image image The image from Robotino&#39; camera To set the image r...",""],
["robotino_camera_dialog.htm","Dialog","Dialog Shows the latest image. To adjust the image resolution see device dialog . ",""],
["robotino_collisiondetection.htm","Collision detection","Collision detection Here you can find function blocks referring to sensors for detecting obstacles. ",""],
["robotino_dialog.htm","Main dialog","Main dialog The dialog of the Robotino device will be shown after double-clicking on the Robotino device. 1 IP address input Robotino&#39;s default IP...",""],
["robotino_digitalinput.htm","Digital Input","Digital Input Reads the value of a digital input. Outputs Type Description Value bool The value at Robotino&#39;s I/O connector. Voltages less 5.75V a...",""],
["robotino_digitaloutput.htm","Digital Output","Digital Output Set a digital output. Inputs Type Default Description Value bool false If true the output at Robotino&#39;s I/O connector is +10V. Othe...",""],
["robotino_distance.htm","Distance sensors","Distance sensors The sensor reading of a distance sensor. Inputs Type Unit Default Description Outputs Value float Volt Analog reading of the dist...",""],
["robotino_distancesensor_example.htm","Example","Example The data sheet of the distance sensor (its a Sharp GP2D120) shows the mapping between distance to an object in cm and the sensor&#39;s analog ...",""],
["robotino_drivesystem.htm","Drivesystem","Drive system This folder contains function blocks to control Robotino&#39;s drive system. ",""],
["robotino_drivesystem_functionblock.htm","Drive System","Drive System This function block directly controls Robotino&#39;s drive system. Eingänge Typ Einheit Standard Beschreibung vx float mm/s 0 Set-speed i...",""],
["robotino_encoderinput.htm","Encoder input","Encoder input This function block reads values from Robotino&#39;s encoder input. The encoder input interprets signals from a digital motor encoder (A...",""],
["robotino_functionblocks.htm","Functionblocks","Function blocks The function blocks allow the usage of the Robotino device in a subprogram. ",""],
["robotino_gripper.htm","Gripper","Gripper Use this module with a Festo Robotino Gripper. The Gripper can only be used if the current sub-program does not contain a power output . I...",""],
["robotino_imagesystem.htm","Imagesystem","Image system This folder contains function blocks to use Robotino&#39;s camera. ",""],
["robotino_internalsensors.htm","Internal sensors","Internal sensors ",""],
["robotino_ioconnector.htm","I/O connector","I/O connector Here you can find function blocks to access Robotino&#39;s I/O connector. ",""],
["robotino_ioextension.htm","I/O extension","I/O extension This folder contains function blocks to Robotino&#39;s other hardware interfaces. ",""],
["robotino_motor.htm","Motor","Motor Access to one Robotino&#39;s motors. The motor number is displayed. . Inputs Type Unit Default Description Speed set-point float rpm 0 The speed...",""],
["robotino_motor_dialog.htm","Dialog","Dialog Parameter Description Acceleration Acceleration/Deceleration factor. With the maximum value 100 speed set-points are given directly to the ...",""],
["robotino_navigation.htm","Navigation","Navigation This folder contains function blocks for the location of Robotino. ",""],
["robotino_northstar.htm","North Star","North Star North Star &#174; is a sensor which determines Robotino&#174;&#39;s absolute position with the help of projectors. Inputs Type Unit Default Descripti...",""],
["robotino_northstar_dialog.htm","Dialog","Dialog Spot A Intensity of the first light spot emitted by the projector. Spot B Intensity of the second light spot emitted by the projector. Curr...",""],
["robotino_northstar_example.htm","Example","Example The control panel is used to move Robotino. Northstar shall detect the projector that belongs to room 4. The new NorthStar projector must ...",""],
["robotino_odometry.htm","Odometrie","Odometry For this functionality a 1GB Compact-Flash memory card for Robotino (V 1.7 or higher) is needed. (No functionality with 256MB memory card...",""],
["robotino_omnidrive.htm","Omnidrive","Omnidrive Calculates the speed set-points of motor 1, 2 and 3 according to set-velocities vx, vy and omega. Inputs Type Unit Default Description v...",""],
["robotino_omnidrive_inv.htm","Omniantrieb Invers","Omniantrieb Invers Calculates actual velocity and rotational velocity from single motor speeds. Eingänge m1 float rpm Motor 1 speed. m2 float rpm ...",""],
["robotino_powermanagement.htm","Power management","Power management The power management module of Robotino. Inputs Type Unit Default Description Outputs Power consumption float A The current drawn...",""],
["robotino_poweroutput.htm","Power output","Power output This function block assigns set point values to Robotino&#39;s power output (former Motor 4). The power output can only be used if the su...",""],
["robotino_relais.htm","Relay","Relay Switch relay 1 and 2. Inputs Type Default Description Value bool false If false the relay is switched off. The connectors for relay 1 are RE...",""],
["robotino_shutdown.htm","Shutdown","Shutdown Shut down and switch off Robotino. Inputs Type Default Description Shutdown bool false If true, Robotino shuts down and is turned off. ",""],
["robotino_toolbar.htm","Toolbar","Toolbar You can find the IP address input field and connect button within the main tool bar . The IP address input and connect button refer to the...",""],
["robotino_xt_bellows_numbering.htm","Bellows numbering","Bellows numbering ",""],
["rs.htm","Latching relay","Latching relay Output Q is set by input S. Input R resets output Q. See type conversion how numbers are converted to bool. Inputs Type Default Des...",""],
["rs_dialog.htm","Dialog","Dialog Enter topic text here. ",""],
["run_mainprogram.htm","Execute the main program","Execute the main program By clicking on Start\" in the tool bar , simulation of the currently visible program is started. If the sub-program \"Step1...",""],
["run_program.htm","Execute a sub-program","Execute a sub-program After connecting the \" Arbitrary Waveform Generator \" to the \" Counter Up \" you can start simulation of the sub-program by c...",""],
["sample_hold.htm","Sample and Hold","Sample and hold element If Sample is set false, the signal at Input can be kept at the current value. See type conversion how numbers are converte...",""],
["scope.htm","Oscilloscope","Oscilloscope The Oscilloscope is used to visualize up to 16 channels. Inputs Type Default Description Channel 0 float 0 Channel 1 float 0 ... Chan...",""],
["scope_dialog.htm","Dialog","Dialog The dialog visualizes the signals on the channels.For every channel, settings can be changed, like amplification, e.g. It is also possible ...",""],
["segmenter.htm","Segmenter","Segmenter This function block only exists for compatibility reasons. Please use the color range finder instead. The Segmenter function block parti...",""],
["segmentextractor.htm","Segment Extrahierer","Segment Extractor This function block only exists for compatibility reasons. Please use the Segment tracker instead. Get the position and size of ...",""],
["statusbar.htm","Statusleiste","Statusleiste zeigt an, dass eine Verbindung zum Robotino&#174; View Update-Server besteht. zeigt an, dass die Verbindung zum Robotino&#174; View Update-Serv...",""],
["structure_and_concept_of_the_workspace.htm","Structure and concept of user interface","Structure and concept of user interface When starting up Robotino&#174; View an empty project with a single \"Robotino\" device is opened. The complete w...",""],
["subprogram_navigation.htm","Navigate in sub-programs","Navigate in sub-programs At startup a sub-programs zoom level is chosen so that the whole program is visible. You can get this fitted view by the ...",""],
["subtraction.htm","Subtraction","Subtraction The Subtraction function block calculates the difference between the minuend and up to 10 subtrahends. See also http://en.wikipedia.or...",""],
["terminology.htm","Terminology","Terminology Function block Smallest function unit a subprogram consists of. By networking several function blocks it is possible to realise comple...",""],
["time.htm","Timer","Timer Measures the time in milliseconds since program start. If reset is true, the measurement is restarted. Inputs Type Default Description Reset...",""],
["toolbar.htm","Tool bar","Tool bar Create a new project Create a new sub-program Open an existing project Save current project Start main program Start the currently visibl...",""],
["transferfunction.htm","Transfer Function","Transfer Function With the transfer function, it is possible to realize any mapping of the input x to the output y. Inputs Type Default Descriptio...",""],
["tutorial_2.htm","Tutorial 2","Tutorial 2 This exercise shows how a control program with alternative branches is created. The complete program is located int the file examples/s...",""],
["typkonvertierung.htm","Type conversion","Type conversion Data type implicit conversion to Description int float, bool Conversion to bool will result in true if the value is not 0. float i...",""],
["updates.htm","Updates","Updates Robotino View has an online update feature. To check the availability of a new software version, select \"Check For Updates\" in the \"Extras...",""],
["update_robotino.htm","Upgrade Robotino packages","Upgrade Robotino packages Robotino&#39;s web-interface provides functionallity update Robotino. Use a web-browser (we recommend Google Chrome) to visi...",""],
["upload_to_robotino.htm","Upload and execute projects on Robotino","Upload projects to Robotino and execute them Robotino&#39;s web-interface provides functionallity to upload and execute programs. Use a web-browser (w...",""],
["valuereader.htm","Value reader","Value reader Reads values from a file line by line, separates them at space characters and outputs all values in a line as float array. After the ...",""],
["valuereader_dialog.htm","Dialog","Dialog From top to bottom: File: The file from which the values are read. Step: The line currently being read. ",""],
["valuewriter.htm","Value writer","Value writer Writes the input values into a new line in a file, separated by tabs. Inputs Type Default Description Input float array The data to b...",""],
["valuewriter_dialog.htm","Dialog","Dialog From top to bottom: File: The file into which the values are written. Append: If checked, the values are appended to an existing file. Othe...",""],
["vectormath_elementoperations.htm","Element operations","Element operations ",""],
["vectormath_transformations.htm","Transformations","Transformations ",""],
["vectormath_transformations_rotate_example.htm","Example","Example ",""],
["vectormath_vectoroperations.htm","Vector operations","Vector operations ",""],
["vectormath_vectoroperations_length.htm","Norm","Norm Calculates the Euclidean norm of the input vector. See also http://en.wikipedia.org/wiki/Vector_norm . Inputs Type Default Description Vector...",""],
["vectormath_vectoroperations_length_example.htm","Example","Example The norm of vector (1, 1) is square root of 1+1 = 1.41421.... ",""],
["vector_addition.htm","Addition","Addition The Vector-Addition function block adds up to 10 summands. See also http://en.wikipedia.org/wiki/Vector_addition#Vector_addition_and_subt...",""],
["vector_addition_dialog.htm","Dialog","Dialog ",""],
["vector_dot.htm","Dot product","Dot product Gives the scalar product (or dot product) of two vectors. See also http://en.wikipedia.org/wiki/Scalar_product . Inputs Type Default D...",""],
["vector_element_addtion.htm","Addition","Addition Per element addition of Summand to Vector. Inputs Type Default Description Vector vector2f (0, 0) Summand float 0 Outputs Result vector2f...",""],
["vector_element_division.htm","Division","Division Per element division of Vector by Divisor. Inputs Type Default Description Vector vector2f (0, 0) Divisor float 1 Outputs Result vector2f...",""],
["vector_element_multiplication.htm","Multiplication","Multiplication Per element multiplication of vector by factor. Inputs Type Default Description Vector vector2f (0, 0) Factor float 1 Outputs Resul...",""],
["vector_element_subtraction.htm","Subtraction","Subtraction Per element subtraction of Minuend from Vector. Inputs Type Default Description Vector vector2f (0, 0) Minuend float 0 Outputs Result ...",""],
["vector_math.htm","Vector analysis","Vector analysis This category contains the basic vector analysis methods for two-dimensional vectors. ",""],
["vector_rotate.htm","Rotate","Rotate Rotates the vector by the specified value in degrees. Inputs Type Default Description Vector vector2f (0, 0) Phi float 0 Rotation angle Out...",""],
["vector_subtraction.htm","Subtraction","Subtraction The Subtraction function block calculates the difference between the minuend and up to 10 subtrahends. See also http://en.wikipedia.or...",""],
["vector_subtraction_dialog.htm","Dialog","Dialog ",""],
["vector_to_cartesian.htm","Vector to Cartesian","Vector to Cartesian Split up Vector into its cartesian components. See also http://en.wikipedia.org/wiki/Cartesian_coordinate_system . Inputs Type...",""],
["vector_to_polar.htm","Vector to Polar","Vector to Polar Split up Vector into its polar components. See also http://en.wikipedia.org/wiki/Polar_coordinate_system . Inputs Type Default Des...",""],
["welcome.htm","Welcome","Welcome Robotino&#174; View is the intuitive graphic programming environment for Robotino&#174;. Robotino&#174; View enables you to create and execute control pr...",""],
["workspace_tour.htm","Familiarisation with the workspace","Familiarisation with the workspace Once you have familiarised yourself with the workspace and the designations used in Robotino&#174; View, it will be ...",""],
["xor.htm","XOR","XOR The Output of the XOR is true if the inputs have different values. See type conversion how numbers are converted to bool. Inputs Type Default ...",""],
["xor_example.htm","Example","Example ",""]];
