IF( WIN32 )
	IF( CMAKE_SIZEOF_VOID_P EQUAL 8 )
		IF(MSVC10)
			STRING( REPLACE "\\" "/" ROBOTINOAPI2_DIR "$ENV{ROBOTINOAPI2_64_VC100_DIR}" )
		ELSEIF(MSVC12)
			STRING( REPLACE "\\" "/" ROBOTINOAPI2_DIR "$ENV{ROBOTINOAPI2_64_VC120_DIR}" )
		ENDIF()
	ELSE( CMAKE_SIZEOF_VOID_P EQUAL 8 )
		IF(MSVC10)
			STRING( REPLACE "\\" "/" ROBOTINOAPI2_DIR "$ENV{ROBOTINOAPI2_32_VC100_DIR}" )
		ELSEIF(MSVC12)
			STRING( REPLACE "\\" "/" ROBOTINOAPI2_DIR "$ENV{ROBOTINOAPI2_32_VC120_DIR}" )
		ENDIF()
	ENDIF( CMAKE_SIZEOF_VOID_P EQUAL 8 )
ELSE( WIN32 )
		STRING( REPLACE "\\" "/" ROBOTINOAPI2_DIR "$ENV{ROBOTINOAPI2_DIR}" )
ENDIF( WIN32 )

IF( NOT ROBOTINOAPI2_DIR )
	IF( WIN32 )
		IF( CMAKE_SIZEOF_VOID_P EQUAL 8 )
			STRING( REPLACE "\\" "/" PROGRAMS "$ENV{ProgramFiles}" )
			SET( ROBOTINOAPI2_DIR "${PROGRAMS}/REC GmbH/robotino/api2" )
		ELSE( CMAKE_SIZEOF_VOID_P EQUAL 8 )
			STRING( REPLACE "\\" "/" PROGRAMS "$ENV{ProgramFiles(x86)}" )
			SET( ROBOTINOAPI2_DIR "${PROGRAMS}/REC GmbH/robotino/api2" )
		ENDIF( CMAKE_SIZEOF_VOID_P EQUAL 8 )
	ELSE( WIN32 )
		SET( ROBOTINOAPI2_DIR "/usr/local/robotino/api2" )
	ENDIF( WIN32 )
ENDIF( NOT ROBOTINOAPI2_DIR )

FIND_PATH(
   ROBOTINOAPI2_INCLUDE_DIR 
   NAMES
   rec/robotino/api2/Com.h
   PATHS
   ${ROBOTINOAPI2_DIR}/include
   NO_DEFAULT_PATH
)

SET( ROBOTINOAPI2_FOUND 0 )

IF( ROBOTINOAPI2_INCLUDE_DIR )
	MARK_AS_ADVANCED( ROBOTINOAPI2_DIR )
	SET( ROBOTINOAPI2_FOUND 1 )
	SET( ROBOTINOAPI2_LIB_DIR "${ROBOTINOAPI2_DIR}/lib" )
	SET( ROBOTINOAPI2_BIN_DIR "${ROBOTINOAPI2_DIR}/bin" )
ELSE( ROBOTINOAPI2_INCLUDE_DIR )
	IF( ROBOTINOAPI2_FIND_REQUIRED )
		MESSAGE(FATAL_ERROR "Could not find robotinoapi2. Download from http://wiki.openrobotino.org")
	ENDIF( ROBOTINOAPI2_FIND_REQUIRED )
ENDIF( ROBOTINOAPI2_INCLUDE_DIR )

FIND_LIBRARY(
  REC_ROBOTINO_API2_RELEASE_LIBRARY
  NAMES rec_robotino_api2
  PATHS "${ROBOTINOAPI2_LIB_DIR}"
)

FIND_LIBRARY(
  REC_ROBOTINO_API2_JOYSTICK_RELEASE_LIBRARY
  NAMES rec_joystick
  PATHS "${ROBOTINOAPI2_LIB_DIR}"
)

IF( WIN32 )
	FIND_LIBRARY(
		REC_ROBOTINO_API2_DEBUG_LIBRARY
		NAMES rec_robotino_api2d
		PATHS "${ROBOTINOAPI2_LIB_DIR}"
	)
	
	FIND_FILE( REC_ROBOTINO_API2_DLL rec_robotino_api2.dll PATHS "${ROBOTINOAPI2_BIN_DIR}" NO_DEFAULT_PATH )
	FIND_FILE( REC_ROBOTINO_API2D_DLL rec_robotino_api2d.dll PATHS "${ROBOTINOAPI2_BIN_DIR}" NO_DEFAULT_PATH )
	FILE( GLOB REC_ROBOTINO_API2_PDBS "${ROBOTINOAPI2_BIN_DIR}/*.pdb" )

	SET(
		ROBOTINOAPI2_RELEASE_DLLS
		${REC_ROBOTINO_API2_DLL}
	)

	SET(
		ROBOTINOAPI2_DEBUG_DLLS
		${REC_ROBOTINO_API2D_DLL}
	)

	FIND_LIBRARY(
	  REC_ROBOTINO_API2_JOYSTICK_DEBUG_LIBRARY
	  NAMES rec_joystickd
	  PATHS "${ROBOTINOAPI2_LIB_DIR}"
	)
ENDIF( WIN32 )

IF( ROBOTINOAPI2_FOUND )
	INCLUDE_DIRECTORIES(
		${ROBOTINOAPI2_INCLUDE_DIR}
	)
	
	IF( WIN32 )
		SET( REC_ROBOTINO_API2_LIBRARY optimized ${REC_ROBOTINO_API2_RELEASE_LIBRARY} debug ${REC_ROBOTINO_API2_DEBUG_LIBRARY} )
		SET( REC_ROBOTINO_API2_JOYSTICK_LIBRARY optimized ${REC_ROBOTINO_API2_JOYSTICK_RELEASE_LIBRARY} debug ${REC_ROBOTINO_API2_JOYSTICK_DEBUG_LIBRARY} )
	ELSE( WIN32 )
		SET( REC_ROBOTINO_API2_LIBRARY ${REC_ROBOTINO_API2_RELEASE_LIBRARY} )
		SET( REC_ROBOTINO_API2_JOYSTICK_LIBRARY ${REC_ROBOTINO_API2_JOYSTICK_RELEASE_LIBRARY} )
	ENDIF( WIN32 )
ENDIF( ROBOTINOAPI2_FOUND )

MACRO( COPY_ROBOTINOAPI2_DLLS releaseTarget debugTarget )
  FOREACH( var ${ROBOTINOAPI2_RELEASE_DLLS} )
    CONFIGURE_FILE( ${var} ${releaseTarget} COPYONLY )
  ENDFOREACH( var )
  FOREACH( var ${ROBOTINOAPI2_DEBUG_DLLS} )
    CONFIGURE_FILE( ${var} ${debugTarget} COPYONLY )
  ENDFOREACH( var )
ENDMACRO( COPY_ROBOTINOAPI2_DLLS )

MACRO( COPY_ROBOTINOAPI2_PDBS releaseTarget debugTarget )
  FOREACH( var ${REC_ROBOTINO_API2_PDBS} )
    CONFIGURE_FILE( ${var} ${releaseTarget} COPYONLY )
  ENDFOREACH( var )
ENDMACRO( COPY_ROBOTINOAPI2_PDBS )
